(in-package :cl-starpu)

(pkg-config-cflags "starpu-1.3")

(include "starpu.h")

(constant (STARPU_MAJOR_VERSION "STARPU_MAJOR_VERSION"))

(constant (STARPU_MINOR_VERSION "STARPU_MINOR_VERSION"))

(constant (STARPU_RELEASE_VERSION "STARPU_RELEASE_VERSION"))

(constant (STARPU_USE_CPU "STARPU_USE_CPU"))

(constant (STARPU_USE_OPENCL "STARPU_USE_OPENCL"))

(constant (STARPU_OPENMP "STARPU_OPENMP"))

(constant (STARPU_HAVE_VALGRIND_H "STARPU_HAVE_VALGRIND_H"))

(constant (STARPU_HAVE_MEMCHECK_H "STARPU_HAVE_MEMCHECK_H"))

(constant (STARPU_NON_BLOCKING_DRIVERS "STARPU_NON_BLOCKING_DRIVERS"))

(constant (STARPU_USE_MPI "STARPU_USE_MPI"))

(constant (STARPU_USE_MPI_MPI "STARPU_USE_MPI_MPI"))

(constant (STARPU_SYSTEM_BLAS "STARPU_SYSTEM_BLAS"))

(constant (STARPU_OPENGL_RENDER "STARPU_OPENGL_RENDER"))

(constant (STARPU_HAVE_X "STARPU_HAVE_X"))

(constant (STARPU_HAVE_POSIX_MEMALIGN "STARPU_HAVE_POSIX_MEMALIGN"))

(constant (STARPU_HAVE_MEMALIGN "STARPU_HAVE_MEMALIGN"))

(constant (STARPU_HAVE_MALLOC_H "STARPU_HAVE_MALLOC_H"))

(constant (STARPU_HAVE_SYNC_BOOL_COMPARE_AND_SWAP "STARPU_HAVE_SYNC_BOOL_COMPARE_AND_SWAP"))

(constant (STARPU_HAVE_SYNC_VAL_COMPARE_AND_SWAP "STARPU_HAVE_SYNC_VAL_COMPARE_AND_SWAP"))

(constant (STARPU_HAVE_SYNC_FETCH_AND_ADD "STARPU_HAVE_SYNC_FETCH_AND_ADD"))

(constant (STARPU_HAVE_SYNC_FETCH_AND_OR "STARPU_HAVE_SYNC_FETCH_AND_OR"))

(constant (STARPU_HAVE_SYNC_LOCK_TEST_AND_SET "STARPU_HAVE_SYNC_LOCK_TEST_AND_SET"))

(constant (STARPU_HAVE_SYNC_SYNCHRONIZE "STARPU_HAVE_SYNC_SYNCHRONIZE"))

(constant (STARPU_HAVE_FFTW "STARPU_HAVE_FFTW"))

(constant (STARPU_HAVE_FFTWF "STARPU_HAVE_FFTWF"))

(constant (STARPU_HAVE_FFTWL "STARPU_HAVE_FFTWL"))

(constant (STARPU_MAXNODES "STARPU_MAXNODES"))

(constant (STARPU_NMAXBUFS "STARPU_NMAXBUFS"))

(constant (STARPU_MAXCPUS "STARPU_MAXCPUS"))

(constant (STARPU_MAXNUMANODES "STARPU_MAXNUMANODES"))

(constant (STARPU_MAXCUDADEVS "STARPU_MAXCUDADEVS"))

(constant (STARPU_MAXOPENCLDEVS "STARPU_MAXOPENCLDEVS"))

(constant (STARPU_MAXMICDEVS "STARPU_MAXMICDEVS"))

(constant (STARPU_NMAXWORKERS "STARPU_NMAXWORKERS"))

(constant (STARPU_NMAX_SCHED_CTXS "STARPU_NMAX_SCHED_CTXS"))

(constant (STARPU_MAXIMPLEMENTATIONS "STARPU_MAXIMPLEMENTATIONS"))

(constant (STARPU_MAXMPKERNELS "STARPU_MAXMPKERNELS"))

(constant (STARPU_HAVE_GLPK_H "STARPU_HAVE_GLPK_H"))

(constant (STARPU_HAVE_LIBNUMA "STARPU_HAVE_LIBNUMA"))

(constant (STARPU_LINUX_SYS "STARPU_LINUX_SYS"))

(constant (STARPU_HAVE_SETENV "STARPU_HAVE_SETENV"))

(constant (STARPU_HAVE_UNSETENV "STARPU_HAVE_UNSETENV"))

(constant (STARPU_HAVE_UNISTD_H "STARPU_HAVE_UNISTD_H"))

(constant (STARPU_HAVE_HDF "STARPU_HAVE_HDF"))

(constant (STARPU_QUICK_CHECK "STARPU_QUICK_CHECK"))

(constant (STARPU_USE_DRAND "STARPU_USE_DRAND"))

(constant (STARPU_USE_ERAND "STARPU_USE_ERAND"))

(constant (STARPU_HAVE_NEARBYINTF "STARPU_HAVE_NEARBYINTF"))

(constant (STARPU_HAVE_RINTF "STARPU_HAVE_RINTF"))

(constant (STARPU_HAVE_HWLOC "STARPU_HAVE_HWLOC"))

(constant (STARPU_HAVE_PTHREAD_SPIN_LOCK "STARPU_HAVE_PTHREAD_SPIN_LOCK"))

(constant (STARPU_HAVE_PTHREAD_BARRIER "STARPU_HAVE_PTHREAD_BARRIER"))

(constant (STARPU_HAVE_PTHREAD_SETNAME_NP "STARPU_HAVE_PTHREAD_SETNAME_NP"))

(constant (STARPU_HAVE_STRUCT_TIMESPEC "STARPU_HAVE_STRUCT_TIMESPEC"))

(constant (STARPU_HAVE_HELGRIND_H "STARPU_HAVE_HELGRIND_H"))

(constant (HAVE_MPI_COMM_F "HAVE_MPI_COMM_F"))

(constant (STARPU_HAVE_CXX "STARPU_HAVE_CXX"))

(constant (STARPU_HAVE_STRERROR_R "STARPU_HAVE_STRERROR_R"))

(constant (STARPU_HAVE_STATEMENT_EXPRESSIONS "STARPU_HAVE_STATEMENT_EXPRESSIONS"))

(constant (STARPU_BACKTRACE_LENGTH "STARPU_BACKTRACE_LENGTH"))

(constant (STARPU_ACQUIRE_NO_NODE "STARPU_ACQUIRE_NO_NODE"))

(constant (STARPU_ACQUIRE_NO_NODE_LOCK_ALL "STARPU_ACQUIRE_NO_NODE_LOCK_ALL"))

(constant (STARPU_DISK_SIZE_MIN "STARPU_DISK_SIZE_MIN"))

(constant (STARPU_COO_GET_OFFSET "STARPU_COO_GET_OFFSET"))

(constant (STARPU_CSR_GET_OFFSET "STARPU_CSR_GET_OFFSET"))

(constant (STARPU_BCSR_GET_OFFSET "STARPU_BCSR_GET_OFFSET"))

(constant (STARPU_MALLOC_PINNED "STARPU_MALLOC_PINNED"))

(constant (STARPU_MALLOC_COUNT "STARPU_MALLOC_COUNT"))

(constant (STARPU_MALLOC_NORECLAIM "STARPU_MALLOC_NORECLAIM"))

(constant (STARPU_MEMORY_WAIT "STARPU_MEMORY_WAIT"))

(constant (STARPU_MEMORY_OVERFLOW "STARPU_MEMORY_OVERFLOW"))

(constant (STARPU_MALLOC_SIMULATION_FOLDED "STARPU_MALLOC_SIMULATION_FOLDED"))

(constant (STARPU_NOWHERE "STARPU_NOWHERE"))

(constant (STARPU_CPU "STARPU_CPU"))

(constant (STARPU_CUDA "STARPU_CUDA"))

(constant (STARPU_OPENCL "STARPU_OPENCL"))

(constant (STARPU_MIC "STARPU_MIC"))

(constant (STARPU_MPI_MS "STARPU_MPI_MS"))

(constant (STARPU_CODELET_SIMGRID_EXECUTE "STARPU_CODELET_SIMGRID_EXECUTE"))

(constant (STARPU_CODELET_SIMGRID_EXECUTE_AND_INJECT "STARPU_CODELET_SIMGRID_EXECUTE_AND_INJECT"))

(constant (STARPU_CODELET_NOPLANS "STARPU_CODELET_NOPLANS"))

(constant (STARPU_CUDA_ASYNC "STARPU_CUDA_ASYNC"))

(constant (STARPU_OPENCL_ASYNC "STARPU_OPENCL_ASYNC"))

(constant (STARPU_MAIN_RAM "STARPU_MAIN_RAM"))

(constant (STARPU_VARIABLE_NBUFFERS "STARPU_VARIABLE_NBUFFERS"))

(constant (STARPU_SPECIFIC_NODE_LOCAL "STARPU_SPECIFIC_NODE_LOCAL"))

(constant (STARPU_SPECIFIC_NODE_CPU "STARPU_SPECIFIC_NODE_CPU"))

(constant (STARPU_SPECIFIC_NODE_SLOW "STARPU_SPECIFIC_NODE_SLOW"))

(constant (STARPU_SPECIFIC_NODE_FAST "STARPU_SPECIFIC_NODE_FAST"))

(constant (STARPU_TASK_TYPE_NORMAL "STARPU_TASK_TYPE_NORMAL"))

(constant (STARPU_TASK_TYPE_INTERNAL "STARPU_TASK_TYPE_INTERNAL"))

(constant (STARPU_TASK_TYPE_DATA_ACQUIRE "STARPU_TASK_TYPE_DATA_ACQUIRE"))

(constant (STARPU_MODE_SHIFT "STARPU_MODE_SHIFT"))

(constant (STARPU_VALUE "STARPU_VALUE"))

(constant (STARPU_CALLBACK "STARPU_CALLBACK"))

(constant (STARPU_CALLBACK_WITH_ARG "STARPU_CALLBACK_WITH_ARG"))

(constant (STARPU_CALLBACK_ARG "STARPU_CALLBACK_ARG"))

(constant (STARPU_PRIORITY "STARPU_PRIORITY"))

(constant (STARPU_EXECUTE_ON_NODE "STARPU_EXECUTE_ON_NODE"))

(constant (STARPU_EXECUTE_ON_DATA "STARPU_EXECUTE_ON_DATA"))

(constant (STARPU_DATA_ARRAY "STARPU_DATA_ARRAY"))

(constant (STARPU_DATA_MODE_ARRAY "STARPU_DATA_MODE_ARRAY"))

(constant (STARPU_TAG "STARPU_TAG"))

(constant (STARPU_HYPERVISOR_TAG "STARPU_HYPERVISOR_TAG"))

(constant (STARPU_FLOPS "STARPU_FLOPS"))

(constant (STARPU_SCHED_CTX "STARPU_SCHED_CTX"))

(constant (STARPU_PROLOGUE_CALLBACK "STARPU_PROLOGUE_CALLBACK"))

(constant (STARPU_PROLOGUE_CALLBACK_ARG "STARPU_PROLOGUE_CALLBACK_ARG"))

(constant (STARPU_PROLOGUE_CALLBACK_POP "STARPU_PROLOGUE_CALLBACK_POP"))

(constant (STARPU_PROLOGUE_CALLBACK_POP_ARG "STARPU_PROLOGUE_CALLBACK_POP_ARG"))

(constant (STARPU_EXECUTE_ON_WORKER "STARPU_EXECUTE_ON_WORKER"))

(constant (STARPU_EXECUTE_WHERE "STARPU_EXECUTE_WHERE"))

(constant (STARPU_TAG_ONLY "STARPU_TAG_ONLY"))

(constant (STARPU_POSSIBLY_PARALLEL "STARPU_POSSIBLY_PARALLEL"))

(constant (STARPU_WORKER_ORDER "STARPU_WORKER_ORDER"))

(constant (STARPU_NODE_SELECTION_POLICY "STARPU_NODE_SELECTION_POLICY"))

(constant (STARPU_NAME "STARPU_NAME"))

(constant (STARPU_CL_ARGS "STARPU_CL_ARGS"))

(constant (STARPU_CL_ARGS_NFREE "STARPU_CL_ARGS_NFREE"))

(constant (STARPU_TASK_DEPS_ARRAY "STARPU_TASK_DEPS_ARRAY"))

(constant (STARPU_TASK_COLOR "STARPU_TASK_COLOR"))

(constant (STARPU_HANDLES_SEQUENTIAL_CONSISTENCY "STARPU_HANDLES_SEQUENTIAL_CONSISTENCY"))

(constant (STARPU_TASK_SYNCHRONOUS "STARPU_TASK_SYNCHRONOUS"))

(constant (STARPU_TASK_END_DEPS_ARRAY "STARPU_TASK_END_DEPS_ARRAY"))

(constant (STARPU_TASK_END_DEP "STARPU_TASK_END_DEP"))

(constant (STARPU_TASK_WORKERIDS "STARPU_TASK_WORKERIDS"))

(constant (STARPU_SEQUENTIAL_CONSISTENCY "STARPU_SEQUENTIAL_CONSISTENCY"))

(constant (STARPU_TASK_PROFILING_INFO "STARPU_TASK_PROFILING_INFO"))

(constant (STARPU_TASK_NO_SUBMITORDER "STARPU_TASK_NO_SUBMITORDER"))

(constant (STARPU_CALLBACK_ARG_NFREE "STARPU_CALLBACK_ARG_NFREE"))

(constant (STARPU_CALLBACK_WITH_ARG_NFREE "STARPU_CALLBACK_WITH_ARG_NFREE"))

(constant (STARPU_PROLOGUE_CALLBACK_ARG_NFREE "STARPU_PROLOGUE_CALLBACK_ARG_NFREE"))

(constant (STARPU_PROLOGUE_CALLBACK_POP_ARG_NFREE "STARPU_PROLOGUE_CALLBACK_POP_ARG_NFREE"))

(constant (STARPU_TASK_SCHED_DATA "STARPU_TASK_SCHED_DATA"))

(constant (STARPU_SHIFTED_MODE_MAX "STARPU_SHIFTED_MODE_MAX"))

(constant (STARPU_SCHED_CTX_POLICY_NAME "STARPU_SCHED_CTX_POLICY_NAME"))

(constant (STARPU_SCHED_CTX_POLICY_STRUCT "STARPU_SCHED_CTX_POLICY_STRUCT"))

(constant (STARPU_SCHED_CTX_POLICY_MIN_PRIO "STARPU_SCHED_CTX_POLICY_MIN_PRIO"))

(constant (STARPU_SCHED_CTX_POLICY_MAX_PRIO "STARPU_SCHED_CTX_POLICY_MAX_PRIO"))

(constant (STARPU_SCHED_CTX_HIERARCHY_LEVEL "STARPU_SCHED_CTX_HIERARCHY_LEVEL"))

(constant (STARPU_SCHED_CTX_NESTED "STARPU_SCHED_CTX_NESTED"))

(constant (STARPU_SCHED_CTX_AWAKE_WORKERS "STARPU_SCHED_CTX_AWAKE_WORKERS"))

(constant (STARPU_SCHED_CTX_POLICY_INIT "STARPU_SCHED_CTX_POLICY_INIT"))

(constant (STARPU_SCHED_CTX_USER_DATA "STARPU_SCHED_CTX_USER_DATA"))

(constant (STARPU_SCHED_CTX_CUDA_NSMS "STARPU_SCHED_CTX_CUDA_NSMS"))

(constant (STARPU_SCHED_CTX_SUB_CTXS "STARPU_SCHED_CTX_SUB_CTXS"))

(constant (STARPU_DEFAULT_PRIO "STARPU_DEFAULT_PRIO"))

(constant (STARPU_PROFILING_DISABLE "STARPU_PROFILING_DISABLE"))

(constant (STARPU_PROFILING_ENABLE "STARPU_PROFILING_ENABLE"))

(constant (STARPU_NS_PER_S "STARPU_NS_PER_S"))

(constant (STARPU_FXT_MAX_FILES "STARPU_FXT_MAX_FILES"))

(constant (STARPU_THREAD_ACTIVE "STARPU_THREAD_ACTIVE"))

(cenum starpu_data_access_mode
       ((:starpu-none "STARPU_NONE"))
       ((:starpu-r "STARPU_R"))
       ((:starpu-w "STARPU_W"))
       ((:starpu-rw "STARPU_RW"))
       ((:starpu-scratch "STARPU_SCRATCH"))
       ((:starpu-redux "STARPU_REDUX"))
       ((:starpu-commute "STARPU_COMMUTE"))
       ((:starpu-ssend "STARPU_SSEND"))
       ((:starpu-locality "STARPU_LOCALITY"))
       ((:starpu-access-mode-max "STARPU_ACCESS_MODE_MAX")))

(cenum starpu_data_interface_id
       ((:starpu-unknown-interface-id "STARPU_UNKNOWN_INTERFACE_ID"))
       ((:starpu-matrix-interface-id "STARPU_MATRIX_INTERFACE_ID"))
       ((:starpu-block-interface-id "STARPU_BLOCK_INTERFACE_ID"))
       ((:starpu-vector-interface-id "STARPU_VECTOR_INTERFACE_ID"))
       ((:starpu-csr-interface-id "STARPU_CSR_INTERFACE_ID"))
       ((:starpu-bcsr-interface-id "STARPU_BCSR_INTERFACE_ID"))
       ((:starpu-variable-interface-id "STARPU_VARIABLE_INTERFACE_ID"))
       ((:starpu-void-interface-id "STARPU_VOID_INTERFACE_ID"))
       ((:starpu-multiformat-interface-id "STARPU_MULTIFORMAT_INTERFACE_ID"))
       ((:starpu-coo-interface-id "STARPU_COO_INTERFACE_ID"))
       ((:starpu-max-interface-id "STARPU_MAX_INTERFACE_ID")))

(cenum starpu_codelet_type
       ((:starpu-seq "STARPU_SEQ"))
       ((:starpu-spmd "STARPU_SPMD"))
       ((:starpu-forkjoin "STARPU_FORKJOIN")))

(cenum starpu_task_status
       ((:starpu-task-invalid "STARPU_TASK_INVALID"))
       ((:starpu-task-blocked "STARPU_TASK_BLOCKED"))
       ((:starpu-task-ready "STARPU_TASK_READY"))
       ((:starpu-task-running "STARPU_TASK_RUNNING"))
       ((:starpu-task-finished "STARPU_TASK_FINISHED"))
       ((:starpu-task-blocked-on-tag "STARPU_TASK_BLOCKED_ON_TAG"))
       ((:starpu-task-blocked-on-task "STARPU_TASK_BLOCKED_ON_TASK"))
       ((:starpu-task-blocked-on-data "STARPU_TASK_BLOCKED_ON_DATA"))
       ((:starpu-task-stopped "STARPU_TASK_STOPPED")))

(cenum starpu_node_kind
       ((:starpu-unused "STARPU_UNUSED"))
       ((:starpu-cpu-ram "STARPU_CPU_RAM"))
       ((:starpu-cuda-ram "STARPU_CUDA_RAM"))
       ((:starpu-opencl-ram "STARPU_OPENCL_RAM"))
       ((:starpu-disk-ram "STARPU_DISK_RAM"))
       ((:starpu-mic-ram "STARPU_MIC_RAM"))
       ((:starpu-mpi-ms-ram "STARPU_MPI_MS_RAM")))

(cenum starpu_worker_archtype
       ((:starpu-cpu-worker "STARPU_CPU_WORKER"))
       ((:starpu-cuda-worker "STARPU_CUDA_WORKER"))
       ((:starpu-opencl-worker "STARPU_OPENCL_WORKER"))
       ((:starpu-mic-worker "STARPU_MIC_WORKER"))
       ((:starpu-mpi-ms-worker "STARPU_MPI_MS_WORKER"))
       ((:starpu-any-worker "STARPU_ANY_WORKER")))

(cenum starpu_worker_collection_type
       ((:starpu-worker-tree "STARPU_WORKER_TREE"))
       ((:starpu-worker-list "STARPU_WORKER_LIST")))

(cenum starpu_perfmodel_type
       ((:starpu-perfmodel-invalid "STARPU_PERFMODEL_INVALID"))
       ((:starpu-per-arch "STARPU_PER_ARCH"))
       ((:starpu-common "STARPU_COMMON"))
       ((:starpu-history-based "STARPU_HISTORY_BASED"))
       ((:starpu-regression-based "STARPU_REGRESSION_BASED"))
       ((:starpu-nl-regression-based "STARPU_NL_REGRESSION_BASED"))
       ((:starpu-multiple-regression-based "STARPU_MULTIPLE_REGRESSION_BASED")))
