(in-package #:cl-starpu)

(cffi:define-foreign-library libstarpu
  (:unix (:or "libstarpu-1.3.so" "libstarpu-1.3.so.2"))
  (t (:default "libstarpu-1.3")))

(cffi:use-foreign-library libstarpu)

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


(cffi:defcfun ("starpu_pthread_mutex_lock_sched" #.(swig-lispify "starpu_pthread_mutex_lock_sched" 'function)) :int
  (mutex :pointer))

(cffi:defcfun ("starpu_pthread_mutex_unlock_sched" #.(swig-lispify "starpu_pthread_mutex_unlock_sched" 'function)) :int
  (mutex :pointer))

(cffi:defcfun ("starpu_pthread_mutex_trylock_sched" #.(swig-lispify "starpu_pthread_mutex_trylock_sched" 'function)) :int
  (mutex :pointer))

(cffi:defcfun ("starpu_pthread_mutex_check_sched" #.(swig-lispify "starpu_pthread_mutex_check_sched" 'function)) :void
  (mutex :pointer)
  (file :string)
  (line :int))

(cffi:defcfun ("starpu_sem_trywait" #.(swig-lispify "starpu_sem_trywait" 'function)) :int
  (arg0 :pointer))

(cffi:defcfun ("starpu_sem_wait" #.(swig-lispify "starpu_sem_wait" 'function)) :int
  (arg0 :pointer))

(cffi:defcfun ("_starpu_pthread_mutex_trylock" #.(swig-lispify "_starpu_pthread_mutex_trylock" 'function)) :int
  (mutex :pointer)
  (file :string)
  (line :int))

(cffi:defcfun ("_starpu_pthread_mutex_trylock_sched" #.(swig-lispify "_starpu_pthread_mutex_trylock_sched" 'function)) :int
  (mutex :pointer)
  (file :string)
  (line :int))

(cffi:defcfun ("_starpu_pthread_rwlock_tryrdlock" #.(swig-lispify "_starpu_pthread_rwlock_tryrdlock" 'function)) :int
  (rwlock :pointer)
  (file :string)
  (line :int))

(cffi:defcfun ("_starpu_pthread_rwlock_trywrlock" #.(swig-lispify "_starpu_pthread_rwlock_trywrlock" 'function)) :int
  (rwlock :pointer)
  (file :string)
  (line :int))

(cffi:defcfun ("starpu_data_set_name" #.(swig-lispify "starpu_data_set_name" 'function)) :void
  (handle :pointer)
  (name :string))

(cffi:defcfun ("starpu_data_set_coordinates_array" #.(swig-lispify "starpu_data_set_coordinates_array" 'function)) :void
  (handle :pointer)
  (dimensions :int)
  (dims :pointer))

(cffi:defcfun ("starpu_data_set_coordinates" #.(swig-lispify "starpu_data_set_coordinates" 'function)) :void
  (handle :pointer)
  (dimensions :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_data_unregister" #.(swig-lispify "starpu_data_unregister" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_unregister_no_coherency" #.(swig-lispify "starpu_data_unregister_no_coherency" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_unregister_submit" #.(swig-lispify "starpu_data_unregister_submit" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_invalidate" #.(swig-lispify "starpu_data_invalidate" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_invalidate_submit" #.(swig-lispify "starpu_data_invalidate_submit" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_advise_as_important" #.(swig-lispify "starpu_data_advise_as_important" 'function)) :void
  (handle :pointer)
  (is_important :unsigned-int))

(cffi:defcfun ("starpu_data_acquire" #.(swig-lispify "starpu_data_acquire" 'function)) :int
  (handle :pointer)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname)))

(cffi:defcfun ("starpu_data_acquire_on_node" #.(swig-lispify "starpu_data_acquire_on_node" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname)))

(cffi:defcfun ("starpu_data_acquire_cb" #.(swig-lispify "starpu_data_acquire_cb" 'function)) :int
  (handle :pointer)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer))

(cffi:defcfun ("starpu_data_acquire_on_node_cb" #.(swig-lispify "starpu_data_acquire_on_node_cb" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer))

(cffi:defcfun ("starpu_data_acquire_cb_sequential_consistency" #.(swig-lispify "starpu_data_acquire_cb_sequential_consistency" 'function)) :int
  (handle :pointer)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer)
  (sequential_consistency :int))

(cffi:defcfun ("starpu_data_acquire_on_node_cb_sequential_consistency" #.(swig-lispify "starpu_data_acquire_on_node_cb_sequential_consistency" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer)
  (sequential_consistency :int))

(cffi:defcfun ("starpu_data_acquire_on_node_cb_sequential_consistency_quick" #.(swig-lispify "starpu_data_acquire_on_node_cb_sequential_consistency_quick" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer)
  (sequential_consistency :int)
  (quick :int))

(cffi:defcfun ("starpu_data_acquire_on_node_cb_sequential_consistency_sync_jobids" #.(swig-lispify "starpu_data_acquire_on_node_cb_sequential_consistency_sync_jobids" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname))
  (callback :pointer)
  (arg :pointer)
  (sequential_consistency :int)
  (quick :int)
  (pre_sync_jobid :pointer)
  (post_sync_jobid :pointer))

(cffi:defcfun ("starpu_data_acquire_try" #.(swig-lispify "starpu_data_acquire_try" 'function)) :int
  (handle :pointer)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname)))

(cffi:defcfun ("starpu_data_acquire_on_node_try" #.(swig-lispify "starpu_data_acquire_on_node_try" 'function)) :int
  (handle :pointer)
  (node :int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname)))

(cffi:defcfun ("starpu_data_release" #.(swig-lispify "starpu_data_release" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_release_on_node" #.(swig-lispify "starpu_data_release_on_node" 'function)) :void
  (handle :pointer)
  (node :int))

(cffi:defcfun ("starpu_arbiter_create" #.(swig-lispify "starpu_arbiter_create" 'function)) :pointer)

(cffi:defcfun ("starpu_data_assign_arbiter" #.(swig-lispify "starpu_data_assign_arbiter" 'function)) :void
  (handle :pointer)
  (arbiter :pointer))

(cffi:defcfun ("starpu_arbiter_destroy" #.(swig-lispify "starpu_arbiter_destroy" 'function)) :void
  (arbiter :pointer))

(cffi:defcfun ("starpu_data_request_allocation" #.(swig-lispify "starpu_data_request_allocation" 'function)) :int
  (handle :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_data_fetch_on_node" #.(swig-lispify "starpu_data_fetch_on_node" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (async :unsigned-int))

(cffi:defcfun ("starpu_data_prefetch_on_node" #.(swig-lispify "starpu_data_prefetch_on_node" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (async :unsigned-int))

(cffi:defcfun ("starpu_data_prefetch_on_node_prio" #.(swig-lispify "starpu_data_prefetch_on_node_prio" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (async :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_data_idle_prefetch_on_node" #.(swig-lispify "starpu_data_idle_prefetch_on_node" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (async :unsigned-int))

(cffi:defcfun ("starpu_data_idle_prefetch_on_node_prio" #.(swig-lispify "starpu_data_idle_prefetch_on_node_prio" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (async :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_data_is_on_node" #.(swig-lispify "starpu_data_is_on_node" 'function)) :unsigned-int
  (handle :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_data_wont_use" #.(swig-lispify "starpu_data_wont_use" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_data_set_wt_mask" #.(swig-lispify "starpu_data_set_wt_mask" 'function)) :void
  (handle :pointer)
  (wt_mask :unsigned-int))

(cffi:defcfun ("starpu_data_set_sequential_consistency_flag" #.(swig-lispify "starpu_data_set_sequential_consistency_flag" 'function)) :void
  (handle :pointer)
  (flag :unsigned-int))

(cffi:defcfun ("starpu_data_get_sequential_consistency_flag" #.(swig-lispify "starpu_data_get_sequential_consistency_flag" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_data_get_default_sequential_consistency_flag" #.(swig-lispify "starpu_data_get_default_sequential_consistency_flag" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_data_set_default_sequential_consistency_flag" #.(swig-lispify "starpu_data_set_default_sequential_consistency_flag" 'function)) :void
  (flag :unsigned-int))

(cffi:defcfun ("starpu_data_set_ooc_flag" #.(swig-lispify "starpu_data_set_ooc_flag" 'function)) :void
  (handle :pointer)
  (flag :unsigned-int))

(cffi:defcfun ("starpu_data_get_ooc_flag" #.(swig-lispify "starpu_data_get_ooc_flag" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_data_query_status" #.(swig-lispify "starpu_data_query_status" 'function)) :void
  (handle :pointer)
  (memory_node :int)
  (is_allocated :pointer)
  (is_valid :pointer)
  (is_requested :pointer))

(cffi:defcfun ("starpu_data_set_reduction_methods" #.(swig-lispify "starpu_data_set_reduction_methods" 'function)) :void
  (handle :pointer)
  (redux_cl :pointer)
  (init_cl :pointer))

(cffi:defcfun ("starpu_data_get_interface_ops" #.(swig-lispify "starpu_data_get_interface_ops" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_data_test_if_allocated_on_node" #.(swig-lispify "starpu_data_test_if_allocated_on_node" 'function)) :unsigned-int
  (handle :pointer)
  (memory_node :unsigned-int))

(cffi:defcfun ("starpu_memchunk_tidy" #.(swig-lispify "starpu_memchunk_tidy" 'function)) :void
  (memory_node :unsigned-int))

(cffi:defcfun ("starpu_data_set_user_data" #.(swig-lispify "starpu_data_set_user_data" 'function)) :void
  (handle :pointer)
  (user_data :pointer))

(cffi:defcfun ("starpu_data_get_user_data" #.(swig-lispify "starpu_data_get_user_data" 'function)) :pointer
  (handle :pointer))

(cffi:defcvar ("_starpu_silent" #.(swig-lispify "_starpu_silent" 'variable))
 :int)

(cffi:defcfun ("starpu_getenv" #.(swig-lispify "starpu_getenv" 'function)) :string
  (str :string))

(cffi:defcfun ("starpu_get_env_number" #.(swig-lispify "starpu_get_env_number" 'function)) :int
  (str :string))

(cffi:defcfun ("starpu_get_env_number_default" #.(swig-lispify "starpu_get_env_number_default" 'function)) :int
  (str :string)
  (defval :int))

(cffi:defcfun ("starpu_get_env_float_default" #.(swig-lispify "starpu_get_env_float_default" 'function)) :float
  (str :string)
  (defval :float))

(cffi:defcfun ("starpu_execute_on_each_worker" #.(swig-lispify "starpu_execute_on_each_worker" 'function)) :void
  (func :pointer)
  (arg :pointer)
  (where :unsigned-int))

(cffi:defcfun ("starpu_execute_on_each_worker_ex" #.(swig-lispify "starpu_execute_on_each_worker_ex" 'function)) :void
  (func :pointer)
  (arg :pointer)
  (where :unsigned-int)
  (name :string))

(cffi:defcfun ("starpu_execute_on_specific_workers" #.(swig-lispify "starpu_execute_on_specific_workers" 'function)) :void
  (func :pointer)
  (arg :pointer)
  (num_workers :unsigned-int)
  (workers :pointer)
  (name :string))

(cffi:defcfun ("starpu_timing_now" #.(swig-lispify "starpu_timing_now" 'function)) :double)

(cffi:defcfun ("starpu_data_cpy" #.(swig-lispify "starpu_data_cpy" 'function)) :int
  (dst_handle :pointer)
  (src_handle :pointer)
  (asynchronous :int)
  (callback_func :pointer)
  (callback_arg :pointer))

(cffi:defcvar ("starpu_disk_stdio_ops" #.(swig-lispify "starpu_disk_stdio_ops" 'variable))
 #.(swig-lispify "starpu_disk_ops" 'classname))

(cffi:defcvar ("starpu_disk_hdf5_ops" #.(swig-lispify "starpu_disk_hdf5_ops" 'variable))
 #.(swig-lispify "starpu_disk_ops" 'classname))

(cffi:defcvar ("starpu_disk_unistd_ops" #.(swig-lispify "starpu_disk_unistd_ops" 'variable))
 #.(swig-lispify "starpu_disk_ops" 'classname))

(cffi:defcvar ("starpu_disk_unistd_o_direct_ops" #.(swig-lispify "starpu_disk_unistd_o_direct_ops" 'variable))
 #.(swig-lispify "starpu_disk_ops" 'classname))

(cffi:defcvar ("starpu_disk_leveldb_ops" #.(swig-lispify "starpu_disk_leveldb_ops" 'variable))
 #.(swig-lispify "starpu_disk_ops" 'classname))

(cffi:defcfun ("starpu_disk_close" #.(swig-lispify "starpu_disk_close" 'function)) :void
  (node :unsigned-int)
  (obj :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_disk_open" #.(swig-lispify "starpu_disk_open" 'function)) :pointer
  (node :unsigned-int)
  (pos :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_disk_register" #.(swig-lispify "starpu_disk_register" 'function)) :int
  (func :pointer)
  (parameter :pointer)
  (size :long))

(cffi:defcvar ("starpu_disk_swap_node" #.(swig-lispify "starpu_disk_swap_node" 'variable))
 :int)

(cffi:defcfun ("starpu_data_register" #.(swig-lispify "starpu_data_register" 'function)) :void
  (handleptr :pointer)
  (home_node :int)
  (data_interface :pointer)
  (ops :pointer))

(cffi:defcfun ("starpu_data_ptr_register" #.(swig-lispify "starpu_data_ptr_register" 'function)) :void
  (handle :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_data_register_same" #.(swig-lispify "starpu_data_register_same" 'function)) :void
  (handledst :pointer)
  (handlesrc :pointer))

(cffi:defcfun ("starpu_data_handle_to_pointer" #.(swig-lispify "starpu_data_handle_to_pointer" 'function)) :pointer
  (handle :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_data_pointer_is_inside" #.(swig-lispify "starpu_data_pointer_is_inside" 'function)) :int
  (handle :pointer)
  (node :unsigned-int)
  (ptr :pointer))

(cffi:defcfun ("starpu_data_get_local_ptr" #.(swig-lispify "starpu_data_get_local_ptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_data_get_interface_on_node" #.(swig-lispify "starpu_data_get_interface_on_node" 'function)) :pointer
  (handle :pointer)
  (memory_node :unsigned-int))

(cffi:defcfun ("starpu_data_get_interface_id" #.(swig-lispify "starpu_data_get_interface_id" 'function)) #.(swig-lispify "starpu_data_interface_id" 'enumname)
  (handle :pointer))

(cffi:defcfun ("starpu_data_pack" #.(swig-lispify "starpu_data_pack" 'function)) :int
  (handle :pointer)
  (ptr :pointer)
  (count :pointer))

(cffi:defcfun ("starpu_data_unpack" #.(swig-lispify "starpu_data_unpack" 'function)) :int
  (handle :pointer)
  (ptr :pointer)
  (count :unsigned-long))

(cffi:defcfun ("starpu_data_get_size" #.(swig-lispify "starpu_data_get_size" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_data_get_alloc_size" #.(swig-lispify "starpu_data_get_alloc_size" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_data_lookup" #.(swig-lispify "starpu_data_lookup" 'function)) :pointer
  (ptr :pointer))

(cffi:defcfun ("starpu_data_get_home_node" #.(swig-lispify "starpu_data_get_home_node" 'function)) :int
  (handle :pointer))

(cffi:defcfun ("starpu_data_interface_get_next_id" #.(swig-lispify "starpu_data_interface_get_next_id" 'function)) :int)

(cffi:defcfun ("starpu_interface_copy" #.(swig-lispify "starpu_interface_copy" 'function)) :int
  (src :pointer)
  (src_offset :unsigned-long)
  (src_node :unsigned-int)
  (dst :pointer)
  (dst_offset :unsigned-long)
  (dst_node :unsigned-int)
  (size :unsigned-long)
  (async_data :pointer))

(cffi:defcfun ("starpu_interface_start_driver_copy_async" #.(swig-lispify "starpu_interface_start_driver_copy_async" 'function)) :void
  (src_node :unsigned-int)
  (dst_node :unsigned-int)
  (start :pointer))

(cffi:defcfun ("starpu_interface_end_driver_copy_async" #.(swig-lispify "starpu_interface_end_driver_copy_async" 'function)) :void
  (src_node :unsigned-int)
  (dst_node :unsigned-int)
  (start :double))

(cffi:defcfun ("starpu_interface_data_copy" #.(swig-lispify "starpu_interface_data_copy" 'function)) :void
  (src_node :unsigned-int)
  (dst_node :unsigned-int)
  (size :unsigned-long))

(cffi:defcfun ("starpu_malloc_on_node_flags" #.(swig-lispify "starpu_malloc_on_node_flags" 'function)) :pointer
  (dst_node :unsigned-int)
  (size :unsigned-long)
  (flags :int))

(cffi:defcfun ("starpu_malloc_on_node" #.(swig-lispify "starpu_malloc_on_node" 'function)) :pointer
  (dst_node :unsigned-int)
  (size :unsigned-long))

(cffi:defcfun ("starpu_free_on_node_flags" #.(swig-lispify "starpu_free_on_node_flags" 'function)) :void
  (dst_node :unsigned-int)
  (addr :pointer)
  (size :unsigned-long)
  (flags :int))

(cffi:defcfun ("starpu_free_on_node" #.(swig-lispify "starpu_free_on_node" 'function)) :void
  (dst_node :unsigned-int)
  (addr :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_malloc_on_node_set_default_flags" #.(swig-lispify "starpu_malloc_on_node_set_default_flags" 'function)) :void
  (node :unsigned-int)
  (flags :int))

(cffi:defcvar ("starpu_interface_matrix_ops" #.(swig-lispify "starpu_interface_matrix_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_matrix_data_register" #.(swig-lispify "starpu_matrix_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (ld :unsigned-int)
  (nx :unsigned-int)
  (ny :unsigned-int)
  (elemsize :unsigned-long))

(cffi:defcfun ("starpu_matrix_data_register_allocsize" #.(swig-lispify "starpu_matrix_data_register_allocsize" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (ld :unsigned-int)
  (nx :unsigned-int)
  (ny :unsigned-int)
  (elemsize :unsigned-long)
  (allocsize :unsigned-long))

(cffi:defcfun ("starpu_matrix_ptr_register" #.(swig-lispify "starpu_matrix_ptr_register" 'function)) :void
  (handle :pointer)
  (node :unsigned-int)
  (ptr :pointer)
  (dev_handle :pointer)
  (offset :unsigned-long)
  (ld :unsigned-int))

(cffi:defcfun ("starpu_matrix_get_nx" #.(swig-lispify "starpu_matrix_get_nx" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_matrix_get_ny" #.(swig-lispify "starpu_matrix_get_ny" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_matrix_get_local_ld" #.(swig-lispify "starpu_matrix_get_local_ld" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_matrix_get_local_ptr" #.(swig-lispify "starpu_matrix_get_local_ptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_matrix_get_elemsize" #.(swig-lispify "starpu_matrix_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_matrix_get_allocsize" #.(swig-lispify "starpu_matrix_get_allocsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcvar ("starpu_interface_coo_ops" #.(swig-lispify "starpu_interface_coo_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_coo_data_register" #.(swig-lispify "starpu_coo_data_register" 'function)) :void
  (handleptr :pointer)
  (home_node :int)
  (nx :unsigned-int)
  (ny :unsigned-int)
  (n_values :unsigned-int)
  (columns :pointer)
  (rows :pointer)
  (values :pointer)
  (elemsize :unsigned-long))

(cffi:defcvar ("starpu_interface_block_ops" #.(swig-lispify "starpu_interface_block_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_block_data_register" #.(swig-lispify "starpu_block_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (ldy :unsigned-int)
  (ldz :unsigned-int)
  (nx :unsigned-int)
  (ny :unsigned-int)
  (nz :unsigned-int)
  (elemsize :unsigned-long))

(cffi:defcfun ("starpu_block_ptr_register" #.(swig-lispify "starpu_block_ptr_register" 'function)) :void
  (handle :pointer)
  (node :unsigned-int)
  (ptr :pointer)
  (dev_handle :pointer)
  (offset :unsigned-long)
  (ldy :unsigned-int)
  (ldz :unsigned-int))

(cffi:defcfun ("starpu_block_get_nx" #.(swig-lispify "starpu_block_get_nx" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_ny" #.(swig-lispify "starpu_block_get_ny" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_nz" #.(swig-lispify "starpu_block_get_nz" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_local_ldy" #.(swig-lispify "starpu_block_get_local_ldy" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_local_ldz" #.(swig-lispify "starpu_block_get_local_ldz" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_local_ptr" #.(swig-lispify "starpu_block_get_local_ptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_block_get_elemsize" #.(swig-lispify "starpu_block_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcvar ("starpu_interface_vector_ops" #.(swig-lispify "starpu_interface_vector_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_vector_data_register" #.(swig-lispify "starpu_vector_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (nx :unsigned-int)
  (elemsize :unsigned-long))

(cffi:defcfun ("starpu_vector_data_register_allocsize" #.(swig-lispify "starpu_vector_data_register_allocsize" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (nx :unsigned-int)
  (elemsize :unsigned-long)
  (allocsize :unsigned-long))

(cffi:defcfun ("starpu_vector_ptr_register" #.(swig-lispify "starpu_vector_ptr_register" 'function)) :void
  (handle :pointer)
  (node :unsigned-int)
  (ptr :pointer)
  (dev_handle :pointer)
  (offset :unsigned-long))

(cffi:defcfun ("starpu_vector_get_nx" #.(swig-lispify "starpu_vector_get_nx" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_vector_get_elemsize" #.(swig-lispify "starpu_vector_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_vector_get_allocsize" #.(swig-lispify "starpu_vector_get_allocsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_vector_get_local_ptr" #.(swig-lispify "starpu_vector_get_local_ptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcvar ("starpu_interface_variable_ops" #.(swig-lispify "starpu_interface_variable_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_variable_data_register" #.(swig-lispify "starpu_variable_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_variable_ptr_register" #.(swig-lispify "starpu_variable_ptr_register" 'function)) :void
  (handle :pointer)
  (node :unsigned-int)
  (ptr :pointer)
  (dev_handle :pointer)
  (offset :unsigned-long))

(cffi:defcfun ("starpu_variable_get_elemsize" #.(swig-lispify "starpu_variable_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_variable_get_local_ptr" #.(swig-lispify "starpu_variable_get_local_ptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcvar ("starpu_interface_void_ops" #.(swig-lispify "starpu_interface_void_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_void_data_register" #.(swig-lispify "starpu_void_data_register" 'function)) :void
  (handle :pointer))

(cffi:defcvar ("starpu_interface_csr_ops" #.(swig-lispify "starpu_interface_csr_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_csr_data_register" #.(swig-lispify "starpu_csr_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (nnz :unsigned-int)
  (nrow :unsigned-int)
  (nzval :pointer)
  (colind :pointer)
  (rowptr :pointer)
  (firstentry :unsigned-int)
  (elemsize :unsigned-long))

(cffi:defcfun ("starpu_csr_get_nnz" #.(swig-lispify "starpu_csr_get_nnz" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_nrow" #.(swig-lispify "starpu_csr_get_nrow" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_firstentry" #.(swig-lispify "starpu_csr_get_firstentry" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_local_nzval" #.(swig-lispify "starpu_csr_get_local_nzval" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_local_colind" #.(swig-lispify "starpu_csr_get_local_colind" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_local_rowptr" #.(swig-lispify "starpu_csr_get_local_rowptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_csr_get_elemsize" #.(swig-lispify "starpu_csr_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcvar ("starpu_interface_bcsr_ops" #.(swig-lispify "starpu_interface_bcsr_ops" 'variable))
 #.(swig-lispify "starpu_data_interface_ops" 'classname))

(cffi:defcfun ("starpu_bcsr_data_register" #.(swig-lispify "starpu_bcsr_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (nnz :unsigned-int)
  (nrow :unsigned-int)
  (nzval :pointer)
  (colind :pointer)
  (rowptr :pointer)
  (firstentry :unsigned-int)
  (r :unsigned-int)
  (c :unsigned-int)
  (elemsize :unsigned-long))

(cffi:defcfun ("starpu_bcsr_get_nnz" #.(swig-lispify "starpu_bcsr_get_nnz" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_nrow" #.(swig-lispify "starpu_bcsr_get_nrow" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_firstentry" #.(swig-lispify "starpu_bcsr_get_firstentry" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_local_nzval" #.(swig-lispify "starpu_bcsr_get_local_nzval" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_local_colind" #.(swig-lispify "starpu_bcsr_get_local_colind" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_local_rowptr" #.(swig-lispify "starpu_bcsr_get_local_rowptr" 'function)) :pointer
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_r" #.(swig-lispify "starpu_bcsr_get_r" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_c" #.(swig-lispify "starpu_bcsr_get_c" 'function)) :unsigned-int
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_get_elemsize" #.(swig-lispify "starpu_bcsr_get_elemsize" 'function)) :unsigned-long
  (handle :pointer))

(cffi:defcfun ("starpu_multiformat_data_register" #.(swig-lispify "starpu_multiformat_data_register" 'function)) :void
  (handle :pointer)
  (home_node :int)
  (ptr :pointer)
  (nobjects :unsigned-int)
  (format_ops :pointer))

(cffi:defcfun ("starpu_data_partition" #.(swig-lispify "starpu_data_partition" 'function)) :void
  (initial_handle :pointer)
  (f :pointer))

(cffi:defcfun ("starpu_data_unpartition" #.(swig-lispify "starpu_data_unpartition" 'function)) :void
  (root_data :pointer)
  (gathering_node :unsigned-int))

(cffi:defcfun ("starpu_data_get_child" #.(swig-lispify "starpu_data_get_child" 'function)) :pointer
  (handle :pointer)
  (i :unsigned-int))

(cffi:defcfun ("starpu_data_get_nb_children" #.(swig-lispify "starpu_data_get_nb_children" 'function)) :int
  (handle :pointer))

(cffi:defcfun ("starpu_data_get_sub_data" #.(swig-lispify "starpu_data_get_sub_data" 'function)) :pointer
  (root_data :pointer)
  (depth :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_data_vget_sub_data" #.(swig-lispify "starpu_data_vget_sub_data" 'function)) :pointer
  (root_data :pointer)
  (depth :unsigned-int)
  (pa :pointer))

(cffi:defcfun ("starpu_data_map_filters" #.(swig-lispify "starpu_data_map_filters" 'function)) :void
  (root_data :pointer)
  (nfilters :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_data_vmap_filters" #.(swig-lispify "starpu_data_vmap_filters" 'function)) :void
  (root_data :pointer)
  (nfilters :unsigned-int)
  (pa :pointer))

(cffi:defcfun ("starpu_data_partition_plan" #.(swig-lispify "starpu_data_partition_plan" 'function)) :void
  (initial_handle :pointer)
  (f :pointer)
  (children :pointer))

(cffi:defcfun ("starpu_data_partition_submit" #.(swig-lispify "starpu_data_partition_submit" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer))

(cffi:defcfun ("starpu_data_partition_readonly_submit" #.(swig-lispify "starpu_data_partition_readonly_submit" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer))

(cffi:defcfun ("starpu_data_partition_readwrite_upgrade_submit" #.(swig-lispify "starpu_data_partition_readwrite_upgrade_submit" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer))

(cffi:defcfun ("starpu_data_unpartition_submit" #.(swig-lispify "starpu_data_unpartition_submit" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer)
  (gathering_node :int))

(cffi:defcfun ("starpu_data_unpartition_submit_r" #.(swig-lispify "starpu_data_unpartition_submit_r" 'function)) :void
  (initial_handle :pointer)
  (gathering_node :int))

(cffi:defcfun ("starpu_data_unpartition_readonly_submit" #.(swig-lispify "starpu_data_unpartition_readonly_submit" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer)
  (gathering_node :int))

(cffi:defcfun ("starpu_data_partition_clean" #.(swig-lispify "starpu_data_partition_clean" 'function)) :void
  (root_data :pointer)
  (nparts :unsigned-int)
  (children :pointer))

(cffi:defcfun ("starpu_data_unpartition_submit_sequential_consistency_cb" #.(swig-lispify "starpu_data_unpartition_submit_sequential_consistency_cb" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer)
  (gather_node :int)
  (sequential_consistency :int)
  (callback_func :pointer)
  (callback_arg :pointer))

(cffi:defcfun ("starpu_data_partition_submit_sequential_consistency" #.(swig-lispify "starpu_data_partition_submit_sequential_consistency" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer)
  (sequential_consistency :int))

(cffi:defcfun ("starpu_data_unpartition_submit_sequential_consistency" #.(swig-lispify "starpu_data_unpartition_submit_sequential_consistency" 'function)) :void
  (initial_handle :pointer)
  (nparts :unsigned-int)
  (children :pointer)
  (gathering_node :int)
  (sequential_consistency :int))

(cffi:defcfun ("starpu_data_partition_not_automatic" #.(swig-lispify "starpu_data_partition_not_automatic" 'function)) :void
  (handle :pointer))

(cffi:defcfun ("starpu_bcsr_filter_canonical_block" #.(swig-lispify "starpu_bcsr_filter_canonical_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_bcsr_filter_canonical_block_child_ops" #.(swig-lispify "starpu_bcsr_filter_canonical_block_child_ops" 'function)) :pointer
  (f :pointer)
  (child :unsigned-int))

(cffi:defcfun ("starpu_csr_filter_vertical_block" #.(swig-lispify "starpu_csr_filter_vertical_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_matrix_filter_block" #.(swig-lispify "starpu_matrix_filter_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_matrix_filter_block_shadow" #.(swig-lispify "starpu_matrix_filter_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_matrix_filter_vertical_block" #.(swig-lispify "starpu_matrix_filter_vertical_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_matrix_filter_vertical_block_shadow" #.(swig-lispify "starpu_matrix_filter_vertical_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_vector_filter_block" #.(swig-lispify "starpu_vector_filter_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_vector_filter_block_shadow" #.(swig-lispify "starpu_vector_filter_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_vector_filter_list_long" #.(swig-lispify "starpu_vector_filter_list_long" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_vector_filter_list" #.(swig-lispify "starpu_vector_filter_list" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_vector_filter_divide_in_2" #.(swig-lispify "starpu_vector_filter_divide_in_2" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_block" #.(swig-lispify "starpu_block_filter_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_block_shadow" #.(swig-lispify "starpu_block_filter_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_vertical_block" #.(swig-lispify "starpu_block_filter_vertical_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_vertical_block_shadow" #.(swig-lispify "starpu_block_filter_vertical_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_depth_block" #.(swig-lispify "starpu_block_filter_depth_block" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_block_filter_depth_block_shadow" #.(swig-lispify "starpu_block_filter_depth_block_shadow" 'function)) :void
  (father_interface :pointer)
  (child_interface :pointer)
  (f :pointer)
  (id :unsigned-int)
  (nparts :unsigned-int))

(cffi:defcfun ("starpu_filter_nparts_compute_chunk_size_and_offset" #.(swig-lispify "starpu_filter_nparts_compute_chunk_size_and_offset" 'function)) :void
  (n :unsigned-int)
  (nparts :unsigned-int)
  (elemsize :unsigned-long)
  (id :unsigned-int)
  (ld :unsigned-int)
  (chunk_size :pointer)
  (offset :pointer))

(cffi:defcfun ("starpu_malloc_set_align" #.(swig-lispify "starpu_malloc_set_align" 'function)) :void
  (align :unsigned-long))

(cffi:defcfun ("starpu_malloc" #.(swig-lispify "starpu_malloc" 'function)) :int
  (A :pointer)
  (dim :unsigned-long))

(cffi:defcfun ("starpu_free" #.(swig-lispify "starpu_free" 'function)) :int
  (A :pointer))

(cffi:defcfun ("starpu_malloc_flags" #.(swig-lispify "starpu_malloc_flags" 'function)) :int
  (A :pointer)
  (dim :unsigned-long)
  (flags :int))

(cffi:defcfun ("starpu_free_flags" #.(swig-lispify "starpu_free_flags" 'function)) :int
  (A :pointer)
  (dim :unsigned-long)
  (flags :int))

(cffi:defcfun ("starpu_malloc_set_hooks" #.(swig-lispify "starpu_malloc_set_hooks" 'function)) :void
  (malloc_hook :pointer)
  (free_hook :pointer))

(cffi:defcfun ("starpu_memory_pin" #.(swig-lispify "starpu_memory_pin" 'function)) :int
  (addr :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_memory_unpin" #.(swig-lispify "starpu_memory_unpin" 'function)) :int
  (addr :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_memory_get_total" #.(swig-lispify "starpu_memory_get_total" 'function)) :long
  (node :unsigned-int))

(cffi:defcfun ("starpu_memory_get_available" #.(swig-lispify "starpu_memory_get_available" 'function)) :long
  (node :unsigned-int))

(cffi:defcfun ("starpu_memory_get_total_all_nodes" #.(swig-lispify "starpu_memory_get_total_all_nodes" 'function)) :long)

(cffi:defcfun ("starpu_memory_get_available_all_nodes" #.(swig-lispify "starpu_memory_get_available_all_nodes" 'function)) :long)

(cffi:defcfun ("starpu_memory_allocate" #.(swig-lispify "starpu_memory_allocate" 'function)) :int
  (node :unsigned-int)
  (size :unsigned-long)
  (flags :int))

(cffi:defcfun ("starpu_memory_deallocate" #.(swig-lispify "starpu_memory_deallocate" 'function)) :void
  (node :unsigned-int)
  (size :unsigned-long))

(cffi:defcfun ("starpu_memory_wait_available" #.(swig-lispify "starpu_memory_wait_available" 'function)) :void
  (node :unsigned-int)
  (size :unsigned-long))

(cffi:defcfun ("starpu_sleep" #.(swig-lispify "starpu_sleep" 'function)) :void
  (nb_sec :float))

(cffi:defcfun ("starpu_usleep" #.(swig-lispify "starpu_usleep" 'function)) :void
  (nb_micro_sec :float))

(cffi:defcfun ("starpu_task_bundle_create" #.(swig-lispify "starpu_task_bundle_create" 'function)) :void
  (bundle :pointer))

(cffi:defcfun ("starpu_task_bundle_insert" #.(swig-lispify "starpu_task_bundle_insert" 'function)) :int
  (bundle :pointer)
  (task :pointer))

(cffi:defcfun ("starpu_task_bundle_remove" #.(swig-lispify "starpu_task_bundle_remove" 'function)) :int
  (bundle :pointer)
  (task :pointer))

(cffi:defcfun ("starpu_task_bundle_close" #.(swig-lispify "starpu_task_bundle_close" 'function)) :void
  (bundle :pointer))

(cffi:defcfun ("starpu_task_bundle_expected_length" #.(swig-lispify "starpu_task_bundle_expected_length" 'function)) :double
  (bundle :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_task_bundle_expected_data_transfer_time" #.(swig-lispify "starpu_task_bundle_expected_data_transfer_time" 'function)) :double
  (bundle :pointer)
  (memory_node :unsigned-int))

(cffi:defcfun ("starpu_task_bundle_expected_energy" #.(swig-lispify "starpu_task_bundle_expected_energy" 'function)) :double
  (bundle :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_task_declare_deps_array" #.(swig-lispify "starpu_task_declare_deps_array" 'function)) :void
  (task :pointer)
  (ndeps :unsigned-int)
  (task_array :pointer))

(cffi:defcfun ("starpu_task_declare_deps" #.(swig-lispify "starpu_task_declare_deps" 'function)) :void
  (task :pointer)
  (ndeps :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_task_declare_end_deps_array" #.(swig-lispify "starpu_task_declare_end_deps_array" 'function)) :void
  (task :pointer)
  (ndeps :unsigned-int)
  (task_array :pointer))

(cffi:defcfun ("starpu_task_declare_end_deps" #.(swig-lispify "starpu_task_declare_end_deps" 'function)) :void
  (task :pointer)
  (ndeps :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_task_get_task_succs" #.(swig-lispify "starpu_task_get_task_succs" 'function)) :int
  (task :pointer)
  (ndeps :unsigned-int)
  (task_array :pointer))

(cffi:defcfun ("starpu_task_get_task_scheduled_succs" #.(swig-lispify "starpu_task_get_task_scheduled_succs" 'function)) :int
  (task :pointer)
  (ndeps :unsigned-int)
  (task_array :pointer))

(cffi:defcfun ("starpu_task_end_dep_add" #.(swig-lispify "starpu_task_end_dep_add" 'function)) :void
  (t_arg0 :pointer)
  (nb_deps :int))

(cffi:defcfun ("starpu_task_end_dep_release" #.(swig-lispify "starpu_task_end_dep_release" 'function)) :void
  (t_arg0 :pointer))

(cffi:defcfun ("starpu_tag_declare_deps" #.(swig-lispify "starpu_tag_declare_deps" 'function)) :void
  (id :unsigned-long)
  (ndeps :unsigned-int)
  &rest)

(cffi:defcfun ("starpu_tag_declare_deps_array" #.(swig-lispify "starpu_tag_declare_deps_array" 'function)) :void
  (id :unsigned-long)
  (ndeps :unsigned-int)
  (array :pointer))

(cffi:defcfun ("starpu_tag_wait" #.(swig-lispify "starpu_tag_wait" 'function)) :int
  (id :unsigned-long))

(cffi:defcfun ("starpu_tag_wait_array" #.(swig-lispify "starpu_tag_wait_array" 'function)) :int
  (ntags :unsigned-int)
  (id :pointer))

(cffi:defcfun ("starpu_tag_restart" #.(swig-lispify "starpu_tag_restart" 'function)) :void
  (id :unsigned-long))

(cffi:defcfun ("starpu_tag_remove" #.(swig-lispify "starpu_tag_remove" 'function)) :void
  (id :unsigned-long))

(cffi:defcfun ("starpu_tag_notify_from_apps" #.(swig-lispify "starpu_tag_notify_from_apps" 'function)) :void
  (id :unsigned-long))

(cffi:defcfun ("starpu_tag_get_task" #.(swig-lispify "starpu_tag_get_task" 'function)) :pointer
  (id :unsigned-long))

(cffi:defcfun ("starpu_task_init" #.(swig-lispify "starpu_task_init" 'function)) :void
  (task :pointer))

(cffi:defcfun ("starpu_task_clean" #.(swig-lispify "starpu_task_clean" 'function)) :void
  (task :pointer))

(cffi:defcfun ("starpu_task_create" #.(swig-lispify "starpu_task_create" 'function)) :pointer)

(cffi:defcfun ("starpu_task_destroy" #.(swig-lispify "starpu_task_destroy" 'function)) :void
  (task :pointer))

(cffi:defcfun ("starpu_task_submit" #.(swig-lispify "starpu_task_submit" 'function)) :int
  (task :pointer))

(cffi:defcfun ("starpu_task_submit_to_ctx" #.(swig-lispify "starpu_task_submit_to_ctx" 'function)) :int
  (task :pointer)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_task_finished" #.(swig-lispify "starpu_task_finished" 'function)) :int
  (task :pointer))

(cffi:defcfun ("starpu_task_wait" #.(swig-lispify "starpu_task_wait" 'function)) :int
  (task :pointer))

(cffi:defcfun ("starpu_task_wait_array" #.(swig-lispify "starpu_task_wait_array" 'function)) :int
  (tasks :pointer)
  (nb_tasks :unsigned-int))

(cffi:defcfun ("starpu_task_wait_for_all" #.(swig-lispify "starpu_task_wait_for_all" 'function)) :int)

(cffi:defcfun ("starpu_task_wait_for_n_submitted" #.(swig-lispify "starpu_task_wait_for_n_submitted" 'function)) :int
  (n :unsigned-int))

(cffi:defcfun ("starpu_task_wait_for_all_in_ctx" #.(swig-lispify "starpu_task_wait_for_all_in_ctx" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_task_wait_for_n_submitted_in_ctx" #.(swig-lispify "starpu_task_wait_for_n_submitted_in_ctx" 'function)) :int
  (sched_ctx_id :unsigned-int)
  (n :unsigned-int))

(cffi:defcfun ("starpu_task_wait_for_no_ready" #.(swig-lispify "starpu_task_wait_for_no_ready" 'function)) :int)

(cffi:defcfun ("starpu_task_nready" #.(swig-lispify "starpu_task_nready" 'function)) :int)

(cffi:defcfun ("starpu_task_nsubmitted" #.(swig-lispify "starpu_task_nsubmitted" 'function)) :int)

(cffi:defcfun ("starpu_iteration_push" #.(swig-lispify "starpu_iteration_push" 'function)) :void
  (iteration :unsigned-long))

(cffi:defcfun ("starpu_iteration_pop" #.(swig-lispify "starpu_iteration_pop" 'function)) :void)

(cffi:defcfun ("starpu_do_schedule" #.(swig-lispify "starpu_do_schedule" 'function)) :void)

(cffi:defcfun ("starpu_codelet_init" #.(swig-lispify "starpu_codelet_init" 'function)) :void
  (cl :pointer))

(cffi:defcfun ("starpu_codelet_display_stats" #.(swig-lispify "starpu_codelet_display_stats" 'function)) :void
  (cl :pointer))

(cffi:defcfun ("starpu_task_get_current" #.(swig-lispify "starpu_task_get_current" 'function)) :pointer)

(cffi:defcfun ("starpu_task_get_current_data_node" #.(swig-lispify "starpu_task_get_current_data_node" 'function)) :int
  (i :unsigned-int))

(cffi:defcfun ("starpu_task_get_model_name" #.(swig-lispify "starpu_task_get_model_name" 'function)) :string
  (task :pointer))

(cffi:defcfun ("starpu_task_get_name" #.(swig-lispify "starpu_task_get_name" 'function)) :string
  (task :pointer))

(cffi:defcfun ("starpu_task_dup" #.(swig-lispify "starpu_task_dup" 'function)) :pointer
  (task :pointer))

(cffi:defcfun ("starpu_task_set_implementation" #.(swig-lispify "starpu_task_set_implementation" 'function)) :void
  (task :pointer)
  (impl :unsigned-int))

(cffi:defcfun ("starpu_task_get_implementation" #.(swig-lispify "starpu_task_get_implementation" 'function)) :unsigned-int
  (task :pointer))

(cffi:defcfun ("starpu_create_sync_task" #.(swig-lispify "starpu_create_sync_task" 'function)) :void
  (sync_tag :unsigned-long)
  (ndeps :unsigned-int)
  (deps :pointer)
  (callback :pointer)
  (callback_arg :pointer))

(cffi:defcfun ("starpu_create_callback_task" #.(swig-lispify "starpu_create_callback_task" 'function)) :void
  (callback :pointer)
  (callback_arg :pointer))

(cffi:defcvar ("worker_list" #.(swig-lispify "worker_list" 'variable))
 #.(swig-lispify "starpu_worker_collection" 'classname))

(cffi:defcvar ("worker_tree" #.(swig-lispify "worker_tree" 'variable))
 #.(swig-lispify "starpu_worker_collection" 'classname))

(cffi:defcfun ("starpu_worker_get_count" #.(swig-lispify "starpu_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_cpu_worker_get_count" #.(swig-lispify "starpu_cpu_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_cuda_worker_get_count" #.(swig-lispify "starpu_cuda_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_opencl_worker_get_count" #.(swig-lispify "starpu_opencl_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_mpi_ms_worker_get_count" #.(swig-lispify "starpu_mpi_ms_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_worker_get_id" #.(swig-lispify "starpu_worker_get_id" 'function)) :int)

(cffi:defcfun ("_starpu_worker_get_id_check" #.(swig-lispify "_starpu_worker_get_id_check" 'function)) :unsigned-int
  (f :string)
  (l :int))

(cffi:defcfun ("starpu_worker_get_id_check" #.(swig-lispify "starpu_worker_get_id_check" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_worker_get_bindid" #.(swig-lispify "starpu_worker_get_bindid" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_sched_find_all_worker_combinations" #.(swig-lispify "starpu_sched_find_all_worker_combinations" 'function)) :void)

(cffi:defcfun ("starpu_worker_get_type" #.(swig-lispify "starpu_worker_get_type" 'function)) #.(swig-lispify "starpu_worker_archtype" 'enumname)
  (id :int))

(cffi:defcfun ("starpu_worker_get_count_by_type" #.(swig-lispify "starpu_worker_get_count_by_type" 'function)) :int
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname)))

(cffi:defcfun ("starpu_worker_get_ids_by_type" #.(swig-lispify "starpu_worker_get_ids_by_type" 'function)) :unsigned-int
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname))
  (workerids :pointer)
  (maxsize :unsigned-int))

(cffi:defcfun ("starpu_worker_get_by_type" #.(swig-lispify "starpu_worker_get_by_type" 'function)) :int
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname))
  (num :int))

(cffi:defcfun ("starpu_worker_get_by_devid" #.(swig-lispify "starpu_worker_get_by_devid" 'function)) :int
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname))
  (devid :int))

(cffi:defcfun ("starpu_worker_get_name" #.(swig-lispify "starpu_worker_get_name" 'function)) :void
  (id :int)
  (dst :pointer)
  (maxlen :unsigned-long))

(cffi:defcfun ("starpu_worker_display_names" #.(swig-lispify "starpu_worker_display_names" 'function)) :void
  (output :pointer)
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname)))

(cffi:defcfun ("starpu_worker_get_devid" #.(swig-lispify "starpu_worker_get_devid" 'function)) :int
  (id :int))

(cffi:defcfun ("starpu_worker_get_mp_nodeid" #.(swig-lispify "starpu_worker_get_mp_nodeid" 'function)) :int
  (id :int))

(cffi:defcfun ("starpu_workers_get_tree" #.(swig-lispify "starpu_workers_get_tree" 'function)) :pointer)

(cffi:defcfun ("starpu_worker_get_sched_ctx_list" #.(swig-lispify "starpu_worker_get_sched_ctx_list" 'function)) :unsigned-int
  (worker :int)
  (sched_ctx :pointer))

(cffi:defcfun ("starpu_worker_is_blocked_in_parallel" #.(swig-lispify "starpu_worker_is_blocked_in_parallel" 'function)) :unsigned-int
  (workerid :int))

(cffi:defcfun ("starpu_worker_is_slave_somewhere" #.(swig-lispify "starpu_worker_is_slave_somewhere" 'function)) :unsigned-int
  (workerid :int))

(cffi:defcfun ("starpu_worker_get_type_as_string" #.(swig-lispify "starpu_worker_get_type_as_string" 'function)) :string
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname)))

(cffi:defcfun ("starpu_bindid_get_workerids" #.(swig-lispify "starpu_bindid_get_workerids" 'function)) :int
  (bindid :int)
  (workerids :pointer))

(cffi:defcfun ("starpu_worker_get_devids" #.(swig-lispify "starpu_worker_get_devids" 'function)) :int
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname))
  (devids :pointer)
  (num :int))

(cffi:defcfun ("starpu_worker_get_stream_workerids" #.(swig-lispify "starpu_worker_get_stream_workerids" 'function)) :int
  (devid :unsigned-int)
  (workerids :pointer)
  (type #.(swig-lispify "starpu_worker_archtype" 'enumname)))

(cffi:defcfun ("starpu_worker_get_sched_ctx_id_stream" #.(swig-lispify "starpu_worker_get_sched_ctx_id_stream" 'function)) :unsigned-int
  (stream_workerid :unsigned-int))

(cffi:defcfun ("starpu_worker_get_hwloc_cpuset" #.(swig-lispify "starpu_worker_get_hwloc_cpuset" 'function)) :pointer
  (workerid :int))

(cffi:defcfun ("starpu_worker_get_hwloc_obj" #.(swig-lispify "starpu_worker_get_hwloc_obj" 'function)) :pointer
  (workerid :int))

(cffi:defcfun ("starpu_memory_node_get_devid" #.(swig-lispify "starpu_memory_node_get_devid" 'function)) :int
  (node :unsigned-int))

(cffi:defcfun ("starpu_worker_get_local_memory_node" #.(swig-lispify "starpu_worker_get_local_memory_node" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_worker_get_memory_node" #.(swig-lispify "starpu_worker_get_memory_node" 'function)) :unsigned-int
  (workerid :unsigned-int))

(cffi:defcfun ("starpu_memory_nodes_get_count" #.(swig-lispify "starpu_memory_nodes_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_memory_node_get_name" #.(swig-lispify "starpu_memory_node_get_name" 'function)) :int
  (node :unsigned-int)
  (name :pointer)
  (size :unsigned-long))

(cffi:defcfun ("starpu_memory_nodes_get_numa_count" #.(swig-lispify "starpu_memory_nodes_get_numa_count" 'function)) :int)

(cffi:defcfun ("starpu_memory_nodes_numa_id_to_devid" #.(swig-lispify "starpu_memory_nodes_numa_id_to_devid" 'function)) :int
  (osid :int))

(cffi:defcfun ("starpu_memory_nodes_numa_devid_to_id" #.(swig-lispify "starpu_memory_nodes_numa_devid_to_id" 'function)) :int
  (id :unsigned-int))

(cffi:defcfun ("starpu_node_get_kind" #.(swig-lispify "starpu_node_get_kind" 'function)) #.(swig-lispify "starpu_node_kind" 'enumname)
  (node :unsigned-int))

(cffi:defcfun ("starpu_worker_sched_op_pending" #.(swig-lispify "starpu_worker_sched_op_pending" 'function)) :int)

(cffi:defcfun ("starpu_worker_relax_on" #.(swig-lispify "starpu_worker_relax_on" 'function)) :void)

(cffi:defcfun ("starpu_worker_relax_off" #.(swig-lispify "starpu_worker_relax_off" 'function)) :void)

(cffi:defcfun ("starpu_worker_get_relax_state" #.(swig-lispify "starpu_worker_get_relax_state" 'function)) :int)

(cffi:defcfun ("starpu_worker_lock" #.(swig-lispify "starpu_worker_lock" 'function)) :void
  (workerid :int))

(cffi:defcfun ("starpu_worker_trylock" #.(swig-lispify "starpu_worker_trylock" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_worker_unlock" #.(swig-lispify "starpu_worker_unlock" 'function)) :void
  (workerid :int))

(cffi:defcfun ("starpu_worker_lock_self" #.(swig-lispify "starpu_worker_lock_self" 'function)) :void)

(cffi:defcfun ("starpu_worker_unlock_self" #.(swig-lispify "starpu_worker_unlock_self" 'function)) :void)

(cffi:defcfun ("starpu_combined_worker_get_count" #.(swig-lispify "starpu_combined_worker_get_count" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_worker_is_combined_worker" #.(swig-lispify "starpu_worker_is_combined_worker" 'function)) :unsigned-int
  (id :int))

(cffi:defcfun ("starpu_combined_worker_get_id" #.(swig-lispify "starpu_combined_worker_get_id" 'function)) :int)

(cffi:defcfun ("starpu_combined_worker_get_size" #.(swig-lispify "starpu_combined_worker_get_size" 'function)) :int)

(cffi:defcfun ("starpu_combined_worker_get_rank" #.(swig-lispify "starpu_combined_worker_get_rank" 'function)) :int)

(cffi:defcfun ("starpu_combined_worker_assign_workerid" #.(swig-lispify "starpu_combined_worker_assign_workerid" 'function)) :int
  (nworkers :int)
  (workerid_array :pointer))

(cffi:defcfun ("starpu_combined_worker_get_description" #.(swig-lispify "starpu_combined_worker_get_description" 'function)) :int
  (workerid :int)
  (worker_size :pointer)
  (combined_workerid :pointer))

(cffi:defcfun ("starpu_combined_worker_can_execute_task" #.(swig-lispify "starpu_combined_worker_can_execute_task" 'function)) :int
  (workerid :unsigned-int)
  (task :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_parallel_task_barrier_init" #.(swig-lispify "starpu_parallel_task_barrier_init" 'function)) :void
  (task :pointer)
  (workerid :int))

(cffi:defcfun ("starpu_parallel_task_barrier_init_n" #.(swig-lispify "starpu_parallel_task_barrier_init_n" 'function)) :void
  (task :pointer)
  (worker_size :int))

(cffi:defcfun ("starpu_perfmodel_init" #.(swig-lispify "starpu_perfmodel_init" 'function)) :void
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_load_file" #.(swig-lispify "starpu_perfmodel_load_file" 'function)) :int
  (filename :string)
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_load_symbol" #.(swig-lispify "starpu_perfmodel_load_symbol" 'function)) :int
  (symbol :string)
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_unload_model" #.(swig-lispify "starpu_perfmodel_unload_model" 'function)) :int
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_get_model_path" #.(swig-lispify "starpu_perfmodel_get_model_path" 'function)) :void
  (symbol :string)
  (path :string)
  (maxlen :unsigned-long))

(cffi:defcfun ("starpu_perfmodel_dump_xml" #.(swig-lispify "starpu_perfmodel_dump_xml" 'function)) :void
  (output :pointer)
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_free_sampling_directories" #.(swig-lispify "starpu_perfmodel_free_sampling_directories" 'function)) :void)

(cffi:defcfun ("starpu_worker_get_perf_archtype" #.(swig-lispify "starpu_worker_get_perf_archtype" 'function)) :pointer
  (workerid :int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_perfmodel_get_narch_combs" #.(swig-lispify "starpu_perfmodel_get_narch_combs" 'function)) :int)

(cffi:defcfun ("starpu_perfmodel_arch_comb_add" #.(swig-lispify "starpu_perfmodel_arch_comb_add" 'function)) :int
  (ndevices :int)
  (devices :pointer))

(cffi:defcfun ("starpu_perfmodel_arch_comb_get" #.(swig-lispify "starpu_perfmodel_arch_comb_get" 'function)) :int
  (ndevices :int)
  (devices :pointer))

(cffi:defcfun ("starpu_perfmodel_arch_comb_fetch" #.(swig-lispify "starpu_perfmodel_arch_comb_fetch" 'function)) :pointer
  (comb :int))

(cffi:defcfun ("starpu_perfmodel_get_model_per_arch" #.(swig-lispify "starpu_perfmodel_get_model_per_arch" 'function)) :pointer
  (model :pointer)
  (arch :pointer)
  (impl :unsigned-int))

(cffi:defcfun ("starpu_perfmodel_get_model_per_devices" #.(swig-lispify "starpu_perfmodel_get_model_per_devices" 'function)) :pointer
  (model :pointer)
  (impl :int)
  &rest)

(cffi:defcfun ("starpu_perfmodel_set_per_devices_cost_function" #.(swig-lispify "starpu_perfmodel_set_per_devices_cost_function" 'function)) :int
  (model :pointer)
  (impl :int)
  (func :pointer)
  &rest)

(cffi:defcfun ("starpu_perfmodel_set_per_devices_size_base" #.(swig-lispify "starpu_perfmodel_set_per_devices_size_base" 'function)) :int
  (model :pointer)
  (impl :int)
  (func :pointer)
  &rest)

(cffi:defcfun ("starpu_perfmodel_debugfilepath" #.(swig-lispify "starpu_perfmodel_debugfilepath" 'function)) :void
  (model :pointer)
  (arch :pointer)
  (path :string)
  (maxlen :unsigned-long)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_perfmodel_get_archtype_name" #.(swig-lispify "starpu_perfmodel_get_archtype_name" 'function)) :string
  (archtype #.(swig-lispify "starpu_worker_archtype" 'enumname)))

(cffi:defcfun ("starpu_perfmodel_get_arch_name" #.(swig-lispify "starpu_perfmodel_get_arch_name" 'function)) :void
  (arch :pointer)
  (archname :string)
  (maxlen :unsigned-long)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_perfmodel_history_based_expected_perf" #.(swig-lispify "starpu_perfmodel_history_based_expected_perf" 'function)) :double
  (model :pointer)
  (arch :pointer)
  (footprint :unsigned-int))

(cffi:defcfun ("starpu_perfmodel_initialize" #.(swig-lispify "starpu_perfmodel_initialize" 'function)) :void)

(cffi:defcfun ("starpu_perfmodel_list" #.(swig-lispify "starpu_perfmodel_list" 'function)) :int
  (output :pointer))

(cffi:defcfun ("starpu_perfmodel_print" #.(swig-lispify "starpu_perfmodel_print" 'function)) :void
  (model :pointer)
  (arch :pointer)
  (nimpl :unsigned-int)
  (parameter :string)
  (footprint :pointer)
  (output :pointer))

(cffi:defcfun ("starpu_perfmodel_print_all" #.(swig-lispify "starpu_perfmodel_print_all" 'function)) :int
  (model :pointer)
  (arch :string)
  (parameter :string)
  (footprint :pointer)
  (output :pointer))

(cffi:defcfun ("starpu_perfmodel_print_estimations" #.(swig-lispify "starpu_perfmodel_print_estimations" 'function)) :int
  (model :pointer)
  (footprint :unsigned-int)
  (output :pointer))

(cffi:defcfun ("starpu_perfmodel_list_combs" #.(swig-lispify "starpu_perfmodel_list_combs" 'function)) :int
  (output :pointer)
  (model :pointer))

(cffi:defcfun ("starpu_perfmodel_update_history" #.(swig-lispify "starpu_perfmodel_update_history" 'function)) :void
  (model :pointer)
  (task :pointer)
  (arch :pointer)
  (cpuid :unsigned-int)
  (nimpl :unsigned-int)
  (measured :double))

(cffi:defcfun ("starpu_perfmodel_directory" #.(swig-lispify "starpu_perfmodel_directory" 'function)) :void
  (output :pointer))

(cffi:defcfun ("starpu_bus_print_bandwidth" #.(swig-lispify "starpu_bus_print_bandwidth" 'function)) :void
  (f :pointer))

(cffi:defcfun ("starpu_bus_print_affinity" #.(swig-lispify "starpu_bus_print_affinity" 'function)) :void
  (f :pointer))

(cffi:defcfun ("starpu_bus_print_filenames" #.(swig-lispify "starpu_bus_print_filenames" 'function)) :void
  (f :pointer))

(cffi:defcfun ("starpu_transfer_bandwidth" #.(swig-lispify "starpu_transfer_bandwidth" 'function)) :double
  (src_node :unsigned-int)
  (dst_node :unsigned-int))

(cffi:defcfun ("starpu_transfer_latency" #.(swig-lispify "starpu_transfer_latency" 'function)) :double
  (src_node :unsigned-int)
  (dst_node :unsigned-int))

(cffi:defcfun ("starpu_transfer_predict" #.(swig-lispify "starpu_transfer_predict" 'function)) :double
  (src_node :unsigned-int)
  (dst_node :unsigned-int)
  (size :unsigned-long))

(cffi:defcvar ("starpu_perfmodel_nop" #.(swig-lispify "starpu_perfmodel_nop" 'variable))
 #.(swig-lispify "starpu_perfmodel" 'classname))

(cffi:defcfun ("starpu_task_list_init" #.(swig-lispify "starpu_task_list_init" 'function)) :void
  (list :pointer))

(cffi:defcfun ("starpu_task_list_push_front" #.(swig-lispify "starpu_task_list_push_front" 'function)) :void
  (list :pointer)
  (task :pointer))

(cffi:defcfun ("starpu_task_list_push_back" #.(swig-lispify "starpu_task_list_push_back" 'function)) :void
  (list :pointer)
  (task :pointer))

(cffi:defcfun ("starpu_task_list_front" #.(swig-lispify "starpu_task_list_front" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_back" #.(swig-lispify "starpu_task_list_back" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_empty" #.(swig-lispify "starpu_task_list_empty" 'function)) :int
  (list :pointer))

(cffi:defcfun ("starpu_task_list_erase" #.(swig-lispify "starpu_task_list_erase" 'function)) :void
  (list :pointer)
  (task :pointer))

(cffi:defcfun ("starpu_task_list_pop_front" #.(swig-lispify "starpu_task_list_pop_front" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_pop_back" #.(swig-lispify "starpu_task_list_pop_back" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_begin" #.(swig-lispify "starpu_task_list_begin" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_end" #.(swig-lispify "starpu_task_list_end" 'function)) :pointer
  (list :pointer))

(cffi:defcfun ("starpu_task_list_next" #.(swig-lispify "starpu_task_list_next" 'function)) :pointer
  (task :pointer))

(cffi:defcfun ("starpu_task_list_ismember" #.(swig-lispify "starpu_task_list_ismember" 'function)) :int
  (list :pointer)
  (look :pointer))

(cffi:defcfun ("starpu_task_list_move" #.(swig-lispify "starpu_task_list_move" 'function)) :void
  (ldst :pointer)
  (lsrc :pointer))

(cffi:defcfun ("starpu_task_set" #.(swig-lispify "starpu_task_set" 'function)) :int
  (task :pointer)
  (cl :pointer)
  &rest)

(cffi:defcfun ("starpu_task_build" #.(swig-lispify "starpu_task_build" 'function)) :pointer
  (cl :pointer)
  &rest)

(cffi:defcfun ("starpu_task_insert" #.(swig-lispify "starpu_task_insert" 'function)) :int
  (cl :pointer)
  &rest)

(cffi:defcfun ("starpu_insert_task" #.(swig-lispify "starpu_insert_task" 'function)) :int
  (cl :pointer)
  &rest)

(cffi:defcfun ("starpu_task_insert_data_make_room" #.(swig-lispify "starpu_task_insert_data_make_room" 'function)) :void
  (cl :pointer)
  (task :pointer)
  (allocated_buffers :pointer)
  (current_buffer :int)
  (room :int))

(cffi:defcfun ("starpu_task_insert_data_process_arg" #.(swig-lispify "starpu_task_insert_data_process_arg" 'function)) :void
  (cl :pointer)
  (task :pointer)
  (allocated_buffers :pointer)
  (current_buffer :pointer)
  (arg_type :int)
  (handle :pointer))

(cffi:defcfun ("starpu_task_insert_data_process_array_arg" #.(swig-lispify "starpu_task_insert_data_process_array_arg" 'function)) :void
  (cl :pointer)
  (task :pointer)
  (allocated_buffers :pointer)
  (current_buffer :pointer)
  (nb_handles :int)
  (handles :pointer))

(cffi:defcfun ("starpu_task_insert_data_process_mode_array_arg" #.(swig-lispify "starpu_task_insert_data_process_mode_array_arg" 'function)) :void
  (cl :pointer)
  (task :pointer)
  (allocated_buffers :pointer)
  (current_buffer :pointer)
  (nb_descrs :int)
  (descrs :pointer))

(cffi:defcfun ("starpu_codelet_pack_args" #.(swig-lispify "starpu_codelet_pack_args" 'function)) :void
  (arg_buffer :pointer)
  (arg_buffer_size :pointer)
  &rest)

(cffi:defcfun ("starpu_codelet_pack_arg_init" #.(swig-lispify "starpu_codelet_pack_arg_init" 'function)) :void
  (state :pointer))

(cffi:defcfun ("starpu_codelet_pack_arg" #.(swig-lispify "starpu_codelet_pack_arg" 'function)) :void
  (state :pointer)
  (ptr :pointer)
  (ptr_size :unsigned-long))

(cffi:defcfun ("starpu_codelet_pack_arg_fini" #.(swig-lispify "starpu_codelet_pack_arg_fini" 'function)) :void
  (state :pointer)
  (cl_arg :pointer)
  (cl_arg_size :pointer))

(cffi:defcfun ("starpu_codelet_unpack_args" #.(swig-lispify "starpu_codelet_unpack_args" 'function)) :void
  (cl_arg :pointer)
  &rest)

(cffi:defcfun ("starpu_codelet_unpack_args_and_copyleft" #.(swig-lispify "starpu_codelet_unpack_args_and_copyleft" 'function)) :void
  (cl_arg :pointer)
  (buffer :pointer)
  (buffer_size :unsigned-long)
  &rest)

(cffi:defcfun ("starpu_sched_get_predefined_policies" #.(swig-lispify "starpu_sched_get_predefined_policies" 'function)) :pointer)

(cffi:defcfun ("starpu_worker_get_sched_condition" #.(swig-lispify "starpu_worker_get_sched_condition" 'function)) :void
  (workerid :int)
  (sched_mutex :pointer)
  (sched_cond :pointer))

(cffi:defcfun ("starpu_task_get_job_id" #.(swig-lispify "starpu_task_get_job_id" 'function)) :unsigned-long
  (task :pointer))

(cffi:defcfun ("starpu_sched_get_min_priority" #.(swig-lispify "starpu_sched_get_min_priority" 'function)) :int)

(cffi:defcfun ("starpu_sched_get_max_priority" #.(swig-lispify "starpu_sched_get_max_priority" 'function)) :int)

(cffi:defcfun ("starpu_sched_set_min_priority" #.(swig-lispify "starpu_sched_set_min_priority" 'function)) :int
  (min_prio :int))

(cffi:defcfun ("starpu_sched_set_max_priority" #.(swig-lispify "starpu_sched_set_max_priority" 'function)) :int
  (max_prio :int))

(cffi:defcfun ("starpu_worker_can_execute_task" #.(swig-lispify "starpu_worker_can_execute_task" 'function)) :int
  (workerid :unsigned-int)
  (task :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_worker_can_execute_task_impl" #.(swig-lispify "starpu_worker_can_execute_task_impl" 'function)) :int
  (workerid :unsigned-int)
  (task :pointer)
  (impl_mask :pointer))

(cffi:defcfun ("starpu_worker_can_execute_task_first_impl" #.(swig-lispify "starpu_worker_can_execute_task_first_impl" 'function)) :int
  (workerid :unsigned-int)
  (task :pointer)
  (nimpl :pointer))

(cffi:defcfun ("starpu_push_local_task" #.(swig-lispify "starpu_push_local_task" 'function)) :int
  (workerid :int)
  (task :pointer)
  (back :int))

(cffi:defcfun ("starpu_push_task_end" #.(swig-lispify "starpu_push_task_end" 'function)) :int
  (task :pointer))

(cffi:defcfun ("starpu_get_prefetch_flag" #.(swig-lispify "starpu_get_prefetch_flag" 'function)) :int)

(cffi:defcfun ("starpu_prefetch_task_input_on_node_prio" #.(swig-lispify "starpu_prefetch_task_input_on_node_prio" 'function)) :int
  (task :pointer)
  (node :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_prefetch_task_input_on_node" #.(swig-lispify "starpu_prefetch_task_input_on_node" 'function)) :int
  (task :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_idle_prefetch_task_input_on_node_prio" #.(swig-lispify "starpu_idle_prefetch_task_input_on_node_prio" 'function)) :int
  (task :pointer)
  (node :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_idle_prefetch_task_input_on_node" #.(swig-lispify "starpu_idle_prefetch_task_input_on_node" 'function)) :int
  (task :pointer)
  (node :unsigned-int))

(cffi:defcfun ("starpu_prefetch_task_input_for_prio" #.(swig-lispify "starpu_prefetch_task_input_for_prio" 'function)) :int
  (task :pointer)
  (worker :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_prefetch_task_input_for" #.(swig-lispify "starpu_prefetch_task_input_for" 'function)) :int
  (task :pointer)
  (worker :unsigned-int))

(cffi:defcfun ("starpu_idle_prefetch_task_input_for_prio" #.(swig-lispify "starpu_idle_prefetch_task_input_for_prio" 'function)) :int
  (task :pointer)
  (worker :unsigned-int)
  (prio :int))

(cffi:defcfun ("starpu_idle_prefetch_task_input_for" #.(swig-lispify "starpu_idle_prefetch_task_input_for" 'function)) :int
  (task :pointer)
  (worker :unsigned-int))

(cffi:defcfun ("starpu_task_footprint" #.(swig-lispify "starpu_task_footprint" 'function)) :unsigned-int
  (model :pointer)
  (task :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_task_data_footprint" #.(swig-lispify "starpu_task_data_footprint" 'function)) :unsigned-int
  (task :pointer))

(cffi:defcfun ("starpu_task_expected_length" #.(swig-lispify "starpu_task_expected_length" 'function)) :double
  (task :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_worker_get_relative_speedup" #.(swig-lispify "starpu_worker_get_relative_speedup" 'function)) :double
  (perf_arch :pointer))

(cffi:defcfun ("starpu_task_expected_data_transfer_time" #.(swig-lispify "starpu_task_expected_data_transfer_time" 'function)) :double
  (memory_node :unsigned-int)
  (task :pointer))

(cffi:defcfun ("starpu_task_expected_data_transfer_time_for" #.(swig-lispify "starpu_task_expected_data_transfer_time_for" 'function)) :double
  (task :pointer)
  (worker :unsigned-int))

(cffi:defcfun ("starpu_data_expected_transfer_time" #.(swig-lispify "starpu_data_expected_transfer_time" 'function)) :double
  (handle :pointer)
  (memory_node :unsigned-int)
  (mode #.(swig-lispify "starpu_data_access_mode" 'enumname)))

(cffi:defcfun ("starpu_task_expected_energy" #.(swig-lispify "starpu_task_expected_energy" 'function)) :double
  (task :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_task_expected_conversion_time" #.(swig-lispify "starpu_task_expected_conversion_time" 'function)) :double
  (task :pointer)
  (arch :pointer)
  (nimpl :unsigned-int))

(cffi:defcfun ("starpu_task_notify_ready_soon_register" #.(swig-lispify "starpu_task_notify_ready_soon_register" 'function)) :void
  (f :pointer)
  (data :pointer))

(cffi:defcfun ("starpu_sched_ctx_worker_shares_tasks_lists" #.(swig-lispify "starpu_sched_ctx_worker_shares_tasks_lists" 'function)) :void
  (workerid :int)
  (sched_ctx_id :int))

(cffi:defcfun ("starpu_sched_task_break" #.(swig-lispify "starpu_sched_task_break" 'function)) :void
  (task :pointer))

(cffi:defcfun ("starpu_wake_worker_relax" #.(swig-lispify "starpu_wake_worker_relax" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_wake_worker_no_relax" #.(swig-lispify "starpu_wake_worker_no_relax" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_wake_worker_locked" #.(swig-lispify "starpu_wake_worker_locked" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_wake_worker_relax_light" #.(swig-lispify "starpu_wake_worker_relax_light" 'function)) :int
  (workerid :int))

(cffi:defcfun ("starpu_sched_ctx_create" #.(swig-lispify "starpu_sched_ctx_create" 'function)) :unsigned-int
  (workerids_ctx :pointer)
  (nworkers_ctx :int)
  (sched_ctx_name :string)
  &rest)

(cffi:defcfun ("starpu_sched_ctx_create_inside_interval" #.(swig-lispify "starpu_sched_ctx_create_inside_interval" 'function)) :unsigned-int
  (policy_name :string)
  (sched_ctx_name :string)
  (min_ncpus :int)
  (max_ncpus :int)
  (min_ngpus :int)
  (max_ngpus :int)
  (allow_overlap :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_register_close_callback" #.(swig-lispify "starpu_sched_ctx_register_close_callback" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (close_callback :pointer)
  (args :pointer))

(cffi:defcfun ("starpu_sched_ctx_add_workers" #.(swig-lispify "starpu_sched_ctx_add_workers" 'function)) :void
  (workerids_ctx :pointer)
  (nworkers_ctx :unsigned-int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_remove_workers" #.(swig-lispify "starpu_sched_ctx_remove_workers" 'function)) :void
  (workerids_ctx :pointer)
  (nworkers_ctx :unsigned-int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_display_workers" #.(swig-lispify "starpu_sched_ctx_display_workers" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (f :pointer))

(cffi:defcfun ("starpu_sched_ctx_delete" #.(swig-lispify "starpu_sched_ctx_delete" 'function)) :void
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_set_inheritor" #.(swig-lispify "starpu_sched_ctx_set_inheritor" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (inheritor :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_inheritor" #.(swig-lispify "starpu_sched_ctx_get_inheritor" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_hierarchy_level" #.(swig-lispify "starpu_sched_ctx_get_hierarchy_level" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_set_context" #.(swig-lispify "starpu_sched_ctx_set_context" 'function)) :void
  (sched_ctx_id :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_context" #.(swig-lispify "starpu_sched_ctx_get_context" 'function)) :unsigned-int)

(cffi:defcfun ("starpu_sched_ctx_stop_task_submission" #.(swig-lispify "starpu_sched_ctx_stop_task_submission" 'function)) :void)

(cffi:defcfun ("starpu_sched_ctx_finished_submit" #.(swig-lispify "starpu_sched_ctx_finished_submit" 'function)) :void
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_workers_list" #.(swig-lispify "starpu_sched_ctx_get_workers_list" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int)
  (workerids :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_workers_list_raw" #.(swig-lispify "starpu_sched_ctx_get_workers_list_raw" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int)
  (workerids :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_nworkers" #.(swig-lispify "starpu_sched_ctx_get_nworkers" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_nshared_workers" #.(swig-lispify "starpu_sched_ctx_get_nshared_workers" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int)
  (sched_ctx_id2 :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_contains_worker" #.(swig-lispify "starpu_sched_ctx_contains_worker" 'function)) :unsigned-int
  (workerid :int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_contains_type_of_worker" #.(swig-lispify "starpu_sched_ctx_contains_type_of_worker" 'function)) :unsigned-int
  (arch #.(swig-lispify "starpu_worker_archtype" 'enumname))
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_worker_get_id" #.(swig-lispify "starpu_sched_ctx_worker_get_id" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_ctx_for_task" #.(swig-lispify "starpu_sched_ctx_get_ctx_for_task" 'function)) :unsigned-int
  (task :pointer))

(cffi:defcfun ("starpu_sched_ctx_overlapping_ctxs_on_worker" #.(swig-lispify "starpu_sched_ctx_overlapping_ctxs_on_worker" 'function)) :unsigned-int
  (workerid :int))

(cffi:defcfun ("starpu_sched_ctx_get_user_data" #.(swig-lispify "starpu_sched_ctx_get_user_data" 'function)) :pointer
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_set_user_data" #.(swig-lispify "starpu_sched_ctx_set_user_data" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (user_data :pointer))

(cffi:defcfun ("starpu_sched_ctx_set_policy_data" #.(swig-lispify "starpu_sched_ctx_set_policy_data" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (policy_data :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_policy_data" #.(swig-lispify "starpu_sched_ctx_get_policy_data" 'function)) :pointer
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_sched_policy" #.(swig-lispify "starpu_sched_ctx_get_sched_policy" 'function)) :pointer
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_exec_parallel_code" #.(swig-lispify "starpu_sched_ctx_exec_parallel_code" 'function)) :pointer
  (func :pointer)
  (param :pointer)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_nready_tasks" #.(swig-lispify "starpu_sched_ctx_get_nready_tasks" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_nready_flops" #.(swig-lispify "starpu_sched_ctx_get_nready_flops" 'function)) :double
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_increment" #.(swig-lispify "starpu_sched_ctx_list_task_counters_increment" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (workerid :int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_decrement" #.(swig-lispify "starpu_sched_ctx_list_task_counters_decrement" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (workerid :int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_reset" #.(swig-lispify "starpu_sched_ctx_list_task_counters_reset" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (workerid :int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_increment_all_ctx_locked" #.(swig-lispify "starpu_sched_ctx_list_task_counters_increment_all_ctx_locked" 'function)) :void
  (task :pointer)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_decrement_all_ctx_locked" #.(swig-lispify "starpu_sched_ctx_list_task_counters_decrement_all_ctx_locked" 'function)) :void
  (task :pointer)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_list_task_counters_reset_all" #.(swig-lispify "starpu_sched_ctx_list_task_counters_reset_all" 'function)) :void
  (task :pointer)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_set_priority" #.(swig-lispify "starpu_sched_ctx_set_priority" 'function)) :void
  (workers :pointer)
  (nworkers :int)
  (sched_ctx_id :unsigned-int)
  (priority :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_priority" #.(swig-lispify "starpu_sched_ctx_get_priority" 'function)) :unsigned-int
  (worker :int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_available_cpuids" #.(swig-lispify "starpu_sched_ctx_get_available_cpuids" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (cpuids :pointer)
  (ncpuids :pointer))

(cffi:defcfun ("starpu_sched_ctx_bind_current_thread_to_cpuid" #.(swig-lispify "starpu_sched_ctx_bind_current_thread_to_cpuid" 'function)) :void
  (cpuid :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_book_workers_for_task" #.(swig-lispify "starpu_sched_ctx_book_workers_for_task" 'function)) :int
  (sched_ctx_id :unsigned-int)
  (workerids :pointer)
  (nworkers :int))

(cffi:defcfun ("starpu_sched_ctx_unbook_workers_for_task" #.(swig-lispify "starpu_sched_ctx_unbook_workers_for_task" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (master :int))

(cffi:defcfun ("starpu_sched_ctx_worker_is_master_for_child_ctx" #.(swig-lispify "starpu_sched_ctx_worker_is_master_for_child_ctx" 'function)) :unsigned-int
  (workerid :int)
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_master_get_context" #.(swig-lispify "starpu_sched_ctx_master_get_context" 'function)) :unsigned-int
  (masterid :int))

(cffi:defcfun ("starpu_sched_ctx_revert_task_counters_ctx_locked" #.(swig-lispify "starpu_sched_ctx_revert_task_counters_ctx_locked" 'function)) :void
  (sched_ctx_id :unsigned-int)
  (flops :double))

(cffi:defcfun ("starpu_sched_ctx_move_task_to_ctx_locked" #.(swig-lispify "starpu_sched_ctx_move_task_to_ctx_locked" 'function)) :void
  (task :pointer)
  (sched_ctx :unsigned-int)
  (with_repush :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_worker_rank" #.(swig-lispify "starpu_sched_ctx_get_worker_rank" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_sched_policy_init" #.(swig-lispify "starpu_sched_ctx_get_sched_policy_init" 'function)) :pointer
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_has_starpu_scheduler" #.(swig-lispify "starpu_sched_ctx_has_starpu_scheduler" 'function)) :unsigned-int
  (sched_ctx_id :unsigned-int)
  (awake_workers :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_stream_worker" #.(swig-lispify "starpu_sched_ctx_get_stream_worker" 'function)) :int
  (sub_ctx :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_nsms" #.(swig-lispify "starpu_sched_ctx_get_nsms" 'function)) :int
  (sched_ctx :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_sms_interval" #.(swig-lispify "starpu_sched_ctx_get_sms_interval" 'function)) :void
  (stream_workerid :int)
  (start :pointer)
  (end :pointer))

(cffi:defcfun ("starpu_sched_ctx_get_min_priority" #.(swig-lispify "starpu_sched_ctx_get_min_priority" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_max_priority" #.(swig-lispify "starpu_sched_ctx_get_max_priority" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_set_min_priority" #.(swig-lispify "starpu_sched_ctx_set_min_priority" 'function)) :int
  (sched_ctx_id :unsigned-int)
  (min_prio :int))

(cffi:defcfun ("starpu_sched_ctx_set_max_priority" #.(swig-lispify "starpu_sched_ctx_set_max_priority" 'function)) :int
  (sched_ctx_id :unsigned-int)
  (max_prio :int))

(cffi:defcfun ("starpu_sched_ctx_min_priority_is_set" #.(swig-lispify "starpu_sched_ctx_min_priority_is_set" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_max_priority_is_set" #.(swig-lispify "starpu_sched_ctx_max_priority_is_set" 'function)) :int
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_create_worker_collection" #.(swig-lispify "starpu_sched_ctx_create_worker_collection" 'function)) :pointer
  (sched_ctx_id :unsigned-int)
  (type #.(swig-lispify "starpu_worker_collection_type" 'enumname)))

(cffi:defcfun ("starpu_sched_ctx_delete_worker_collection" #.(swig-lispify "starpu_sched_ctx_delete_worker_collection" 'function)) :void
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_sched_ctx_get_worker_collection" #.(swig-lispify "starpu_sched_ctx_get_worker_collection" 'function)) :pointer
  (sched_ctx_id :unsigned-int))

(cffi:defcfun ("starpu_wake_all_blocked_workers" #.(swig-lispify "starpu_wake_all_blocked_workers" 'function)) :void)

(cffi:defcfun ("starpu_progression_hook_register" #.(swig-lispify "starpu_progression_hook_register" 'function)) :int
  (func :pointer)
  (arg :pointer))

(cffi:defcfun ("starpu_progression_hook_deregister" #.(swig-lispify "starpu_progression_hook_deregister" 'function)) :void
  (hook_id :int))

(cffi:defcfun ("starpu_idle_hook_register" #.(swig-lispify "starpu_idle_hook_register" 'function)) :int
  (func :pointer)
  (arg :pointer))

(cffi:defcfun ("starpu_idle_hook_deregister" #.(swig-lispify "starpu_idle_hook_deregister" 'function)) :void
  (hook_id :int))

(cffi:defcfun ("starpu_cublas_report_error" #.(swig-lispify "starpu_cublas_report_error" 'function)) :void
  (func :string)
  (file :string)
  (line :int)
  (status :int))

(cffi:defcfun ("starpu_cuda_report_error" #.(swig-lispify "starpu_cuda_report_error" 'function)) :void
  (func :string)
  (file :string)
  (line :int)
  (status :pointer))

(cffi:defcfun ("starpu_cuda_get_local_stream" #.(swig-lispify "starpu_cuda_get_local_stream" 'function)) :pointer)

(cffi:defcfun ("starpu_cuda_get_device_properties" #.(swig-lispify "starpu_cuda_get_device_properties" 'function)) :pointer
  (workerid :unsigned-int))

(cffi:defcfun ("starpu_cuda_copy_async_sync" #.(swig-lispify "starpu_cuda_copy_async_sync" 'function)) :int
  (src_ptr :pointer)
  (src_node :unsigned-int)
  (dst_ptr :pointer)
  (dst_node :unsigned-int)
  (ssize :unsigned-long)
  (stream :pointer)
  (kind :pointer))

(cffi:defcfun ("starpu_cuda_set_device" #.(swig-lispify "starpu_cuda_set_device" 'function)) :void
  (devid :unsigned-int))

(cffi:defcfun ("starpu_cublas_init" #.(swig-lispify "starpu_cublas_init" 'function)) :void)

(cffi:defcfun ("starpu_cublas_set_stream" #.(swig-lispify "starpu_cublas_set_stream" 'function)) :void)

(cffi:defcfun ("starpu_cublas_shutdown" #.(swig-lispify "starpu_cublas_shutdown" 'function)) :void)

(cffi:defcfun ("starpu_cusparse_init" #.(swig-lispify "starpu_cusparse_init" 'function)) :void)

(cffi:defcfun ("starpu_cusparse_shutdown" #.(swig-lispify "starpu_cusparse_shutdown" 'function)) :void)

(cffi:defcfun ("starpu_cusparse_get_local_handle" #.(swig-lispify "starpu_cusparse_get_local_handle" 'function)) :pointer)

(cffi:defcfun ("starpu_bound_start" #.(swig-lispify "starpu_bound_start" 'function)) :void
  (deps :int)
  (prio :int))

(cffi:defcfun ("starpu_bound_stop" #.(swig-lispify "starpu_bound_stop" 'function)) :void)

(cffi:defcfun ("starpu_bound_print_dot" #.(swig-lispify "starpu_bound_print_dot" 'function)) :void
  (output :pointer))

(cffi:defcfun ("starpu_bound_compute" #.(swig-lispify "starpu_bound_compute" 'function)) :void
  (res :pointer)
  (integer_res :pointer)
  (integer :int))

(cffi:defcfun ("starpu_bound_print_lp" #.(swig-lispify "starpu_bound_print_lp" 'function)) :void
  (output :pointer))

(cffi:defcfun ("starpu_bound_print_mps" #.(swig-lispify "starpu_bound_print_mps" 'function)) :void
  (output :pointer))

(cffi:defcfun ("starpu_bound_print" #.(swig-lispify "starpu_bound_print" 'function)) :void
  (output :pointer)
  (integer :int))

(cffi:defcfun ("starpu_hash_crc32c_be_n" #.(swig-lispify "starpu_hash_crc32c_be_n" 'function)) :unsigned-int
  (input :pointer)
  (n :unsigned-long)
  (inputcrc :unsigned-int))

(cffi:defcfun ("starpu_hash_crc32c_be" #.(swig-lispify "starpu_hash_crc32c_be" 'function)) :unsigned-int
  (input :unsigned-int)
  (inputcrc :unsigned-int))

(cffi:defcfun ("starpu_hash_crc32c_string" #.(swig-lispify "starpu_hash_crc32c_string" 'function)) :unsigned-int
  (str :string)
  (inputcrc :unsigned-int))

(cffi:defcfun ("starpu_profiling_init" #.(swig-lispify "starpu_profiling_init" 'function)) :void)

(cffi:defcfun ("starpu_profiling_set_id" #.(swig-lispify "starpu_profiling_set_id" 'function)) :void
  (new_id :int))

(cffi:defcfun ("starpu_profiling_status_set" #.(swig-lispify "starpu_profiling_status_set" 'function)) :int
  (status :int))

(cffi:defcfun ("starpu_profiling_status_get" #.(swig-lispify "starpu_profiling_status_get" 'function)) :int)

(cffi:defcfun ("starpu_profiling_worker_get_info" #.(swig-lispify "starpu_profiling_worker_get_info" 'function)) :int
  (workerid :int)
  (worker_info :pointer))

(cffi:defcfun ("starpu_bus_get_count" #.(swig-lispify "starpu_bus_get_count" 'function)) :int)

(cffi:defcfun ("starpu_bus_get_id" #.(swig-lispify "starpu_bus_get_id" 'function)) :int
  (src :int)
  (dst :int))

(cffi:defcfun ("starpu_bus_get_src" #.(swig-lispify "starpu_bus_get_src" 'function)) :int
  (busid :int))

(cffi:defcfun ("starpu_bus_get_dst" #.(swig-lispify "starpu_bus_get_dst" 'function)) :int
  (busid :int))

(cffi:defcfun ("starpu_bus_set_direct" #.(swig-lispify "starpu_bus_set_direct" 'function)) :void
  (busid :int)
  (direct :int))

(cffi:defcfun ("starpu_bus_get_direct" #.(swig-lispify "starpu_bus_get_direct" 'function)) :int
  (busid :int))

(cffi:defcfun ("starpu_bus_set_ngpus" #.(swig-lispify "starpu_bus_set_ngpus" 'function)) :void
  (busid :int)
  (ngpus :int))

(cffi:defcfun ("starpu_bus_get_ngpus" #.(swig-lispify "starpu_bus_get_ngpus" 'function)) :int
  (busid :int))

(cffi:defcfun ("starpu_bus_get_profiling_info" #.(swig-lispify "starpu_bus_get_profiling_info" 'function)) :int
  (busid :int)
  (bus_info :pointer))

(cffi:defcfun ("starpu_timespec_clear" #.(swig-lispify "starpu_timespec_clear" 'function)) :void
  (tsp :pointer))

(cffi:defcfun ("starpu_timespec_add" #.(swig-lispify "starpu_timespec_add" 'function)) :void
  (a :pointer)
  (b :pointer)
  (result :pointer))

(cffi:defcfun ("starpu_timespec_accumulate" #.(swig-lispify "starpu_timespec_accumulate" 'function)) :void
  (result :pointer)
  (a :pointer))

(cffi:defcfun ("starpu_timespec_sub" #.(swig-lispify "starpu_timespec_sub" 'function)) :void
  (a :pointer)
  (b :pointer)
  (result :pointer))

(cffi:defcfun ("starpu_timing_timespec_delay_us" #.(swig-lispify "starpu_timing_timespec_delay_us" 'function)) :double
  (start :pointer)
  (end :pointer))

(cffi:defcfun ("starpu_timing_timespec_to_us" #.(swig-lispify "starpu_timing_timespec_to_us" 'function)) :double
  (ts :pointer))

(cffi:defcfun ("starpu_profiling_bus_helper_display_summary" #.(swig-lispify "starpu_profiling_bus_helper_display_summary" 'function)) :void)

(cffi:defcfun ("starpu_profiling_worker_helper_display_summary" #.(swig-lispify "starpu_profiling_worker_helper_display_summary" 'function)) :void)

(cffi:defcfun ("starpu_data_display_memory_stats" #.(swig-lispify "starpu_data_display_memory_stats" 'function)) :void)

(cffi:defcfun ("starpu_fxt_options_init" #.(swig-lispify "starpu_fxt_options_init" 'function)) :void
  (options :pointer))

(cffi:defcfun ("starpu_fxt_generate_trace" #.(swig-lispify "starpu_fxt_generate_trace" 'function)) :void
  (options :pointer))

(cffi:defcfun ("starpu_fxt_autostart_profiling" #.(swig-lispify "starpu_fxt_autostart_profiling" 'function)) :void
  (autostart :int))

(cffi:defcfun ("starpu_fxt_start_profiling" #.(swig-lispify "starpu_fxt_start_profiling" 'function)) :void)

(cffi:defcfun ("starpu_fxt_stop_profiling" #.(swig-lispify "starpu_fxt_stop_profiling" 'function)) :void)

(cffi:defcfun ("starpu_fxt_write_data_trace" #.(swig-lispify "starpu_fxt_write_data_trace" 'function)) :void
  (filename_in :string))

(cffi:defcfun ("starpu_fxt_trace_user_event" #.(swig-lispify "starpu_fxt_trace_user_event" 'function)) :void
  (code :unsigned-long))

(cffi:defcfun ("starpu_fxt_trace_user_event_string" #.(swig-lispify "starpu_fxt_trace_user_event_string" 'function)) :void
  (s :string))

(cffi:defcfun ("starpu_driver_run" #.(swig-lispify "starpu_driver_run" 'function)) :int
  (d :pointer))

(cffi:defcfun ("starpu_drivers_request_termination" #.(swig-lispify "starpu_drivers_request_termination" 'function)) :void)

(cffi:defcfun ("starpu_driver_init" #.(swig-lispify "starpu_driver_init" 'function)) :int
  (d :pointer))

(cffi:defcfun ("starpu_driver_run_once" #.(swig-lispify "starpu_driver_run_once" 'function)) :int
  (d :pointer))

(cffi:defcfun ("starpu_driver_deinit" #.(swig-lispify "starpu_driver_deinit" 'function)) :int
  (d :pointer))

(cffi:defcfun ("starpu_tree_reset_visited" #.(swig-lispify "starpu_tree_reset_visited" 'function)) :void
  (tree :pointer)
  (visited :string))

(cffi:defcfun ("starpu_tree_prepare_children" #.(swig-lispify "starpu_tree_prepare_children" 'function)) :void
  (arity :unsigned-int)
  (father :pointer))

(cffi:defcfun ("starpu_tree_insert" #.(swig-lispify "starpu_tree_insert" 'function)) :void
  (tree :pointer)
  (id :int)
  (level :int)
  (is_pu :int)
  (arity :int)
  (father :pointer))

(cffi:defcfun ("starpu_tree_get" #.(swig-lispify "starpu_tree_get" 'function)) :pointer
  (tree :pointer)
  (id :int))

(cffi:defcfun ("starpu_tree_get_neighbour" #.(swig-lispify "starpu_tree_get_neighbour" 'function)) :pointer
  (tree :pointer)
  (node :pointer)
  (visited :string)
  (present :string))

(cffi:defcfun ("starpu_tree_free" #.(swig-lispify "starpu_tree_free" 'function)) :void
  (tree :pointer))

(cffi:defcfun ("starpu_bitmap_create" #.(swig-lispify "starpu_bitmap_create" 'function)) :pointer)

(cffi:defcfun ("starpu_bitmap_destroy" #.(swig-lispify "starpu_bitmap_destroy" 'function)) :void
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_set" #.(swig-lispify "starpu_bitmap_set" 'function)) :void
  (b :pointer)
  (e :int))

(cffi:defcfun ("starpu_bitmap_unset" #.(swig-lispify "starpu_bitmap_unset" 'function)) :void
  (b :pointer)
  (e :int))

(cffi:defcfun ("starpu_bitmap_unset_all" #.(swig-lispify "starpu_bitmap_unset_all" 'function)) :void
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_get" #.(swig-lispify "starpu_bitmap_get" 'function)) :int
  (b :pointer)
  (e :int))

(cffi:defcfun ("starpu_bitmap_unset_and" #.(swig-lispify "starpu_bitmap_unset_and" 'function)) :void
  (a :pointer)
  (b :pointer)
  (c :pointer))

(cffi:defcfun ("starpu_bitmap_or" #.(swig-lispify "starpu_bitmap_or" 'function)) :void
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_and_get" #.(swig-lispify "starpu_bitmap_and_get" 'function)) :int
  (b1 :pointer)
  (b2 :pointer)
  (e :int))

(cffi:defcfun ("starpu_bitmap_cardinal" #.(swig-lispify "starpu_bitmap_cardinal" 'function)) :int
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_first" #.(swig-lispify "starpu_bitmap_first" 'function)) :int
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_last" #.(swig-lispify "starpu_bitmap_last" 'function)) :int
  (b :pointer))

(cffi:defcfun ("starpu_bitmap_next" #.(swig-lispify "starpu_bitmap_next" 'function)) :int
  (b :pointer)
  (e :int))

(cffi:defcfun ("starpu_bitmap_has_next" #.(swig-lispify "starpu_bitmap_has_next" 'function)) :int
  (b :pointer)
  (e :int))

(cffi:defcfun ("starpu_conf_init" #.(swig-lispify "starpu_conf_init" 'function)) :int
  (conf :pointer))

(cffi:defcfun ("starpu_init" #.(swig-lispify "starpu_init" 'function)) :int
  (conf :pointer))

(cffi:defcfun ("starpu_initialize" #.(swig-lispify "starpu_initialize" 'function)) :int
  (user_conf :pointer)
  (argc :pointer)
  (argv :pointer))

(cffi:defcfun ("starpu_is_initialized" #.(swig-lispify "starpu_is_initialized" 'function)) :int)

(cffi:defcfun ("starpu_wait_initialized" #.(swig-lispify "starpu_wait_initialized" 'function)) :void)

(cffi:defcfun ("starpu_shutdown" #.(swig-lispify "starpu_shutdown" 'function)) :void)

(cffi:defcfun ("starpu_pause" #.(swig-lispify "starpu_pause" 'function)) :void)

(cffi:defcfun ("starpu_resume" #.(swig-lispify "starpu_resume" 'function)) :void)

(cffi:defcfun ("starpu_get_next_bindid" #.(swig-lispify "starpu_get_next_bindid" 'function)) :unsigned-int
  (flags :unsigned-int)
  (preferred :pointer)
  (npreferred :unsigned-int))

(cffi:defcfun ("starpu_bind_thread_on" #.(swig-lispify "starpu_bind_thread_on" 'function)) :int
  (cpuid :int)
  (flags :unsigned-int)
  (name :string))

(cffi:defcfun ("starpu_topology_print" #.(swig-lispify "starpu_topology_print" 'function)) :void
  (f :pointer))

(cffi:defcfun ("starpu_asynchronous_copy_disabled" #.(swig-lispify "starpu_asynchronous_copy_disabled" 'function)) :int)

(cffi:defcfun ("starpu_asynchronous_cuda_copy_disabled" #.(swig-lispify "starpu_asynchronous_cuda_copy_disabled" 'function)) :int)

(cffi:defcfun ("starpu_asynchronous_opencl_copy_disabled" #.(swig-lispify "starpu_asynchronous_opencl_copy_disabled" 'function)) :int)

(cffi:defcfun ("starpu_asynchronous_mpi_ms_copy_disabled" #.(swig-lispify "starpu_asynchronous_mpi_ms_copy_disabled" 'function)) :int)

(cffi:defcfun ("starpu_display_stats" #.(swig-lispify "starpu_display_stats" 'function)) :void)

(cffi:defcfun ("starpu_get_version" #.(swig-lispify "starpu_get_version" 'function)) :void
  (major :pointer)
  (minor :pointer)
  (release :pointer))


